### ISSUE TITLE
Incomplete / cancelled datasets are shown on local datasets list

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#304]
### Expected behavior

If the downloading of a remote dataset is cancelled, or times out, while it is still loading, then it should not appear in the list of local datasets. 
Alternatively, it should be marked as incomplete. See discussion in #193.

### Actual behavior

The cancelled / incomplete dataset still appears in the list of local datasets. 
The user cannot tell that it is incomplete.

### Steps to reproduce the problem

1.	Open GUI

2.	From ESA CCI Open Data Portal list, select esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1 then click on “Download and/or open remote dataset”

3.	In the “Download Data Source”, enter:
•	Deselect time, region, variable constraints.  
•	Change Unique ID to: local.ozone1
•	Data source title: leave blank
•	Leave “Open after Download” unselected
•	Click “Download” 

![hc047 1](https://user-images.githubusercontent.com/29569434/28822682-0feddcfa-76b2-11e7-9285-b9caa6729377.PNG)

4.	While it is still downloading, cancel it from the Tasks panel.

![hc047 2](https://user-images.githubusercontent.com/29569434/28822695-1c06f67a-76b2-11e7-8b03-dce5dc425197.PNG)

5.	Select Local Data sources. It is shown as a local data source even though the loading was incomplete.

![hc047 3](https://user-images.githubusercontent.com/29569434/28822699-25eebe70-76b2-11e7-965b-2eb3b8c97f9e.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by forman** [comment]
Can only be fixed when #337 is fixed

**Comment by forman** [comment]
Decided to remove `cu_mandatory` label at IRM6.

**Comment by forman** [comment]
Added `cu_review` because new local data sources should now only appear after complete download.

**Comment by HelenClifton** [comment]
Confirmed fixed in cate 0.9.0-dev.7
