### ISSUE TITLE
Show Data in Table causes crash for some resources

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#305]
### Expected behaviour

In the workspace panel, selecting a resource then clicking on “Show data in table”: expect to see a table of data. (It might be a good idea to disable this option for certain types of resources such as datasets).

### Actual behavior

For large resources, clicking “Show data in table” causes memory problems and sometimes machine crashes (it depends on which machine is used and which resource is selected)
Also note it is quite easy to click on “Show data in table” by mistake, when you mean to click on “Resource / step properties”. The two look quite similar.

![hc 050 4](https://user-images.githubusercontent.com/29569434/28822952-40538be6-76b3-11e7-9e19-e4568f74f96b.png)

### Steps to reproduce the problem

1.	Before running these steps, save all work.

2.	Open Windows Task Manager, Processes tab. Sort by memory usage.

3.	In cate, clear workspace or create a new one.

4.	From ESA CCI Open Data Portal list, select esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1 then click on “Download and/or open remote dataset”

5.	In the “Download Data Source” window:
•	Deselect Time, Region, Variable constraints
•	Set Unique ID: local.test.ozone
•	Select “open dataset from local data source after downloading”.
•	Click “Download & Open Local”.

![hc 050 1](https://user-images.githubusercontent.com/29569434/28822852-d16e6ff2-76b2-11e7-8ad6-6a9324b750a5.PNG)

6.	When it has finished downloading, open the Workspace panel if not already open. A new resource has been created called res_1. Highlight the resource then click “Show data in table”

![hc 050 2](https://user-images.githubusercontent.com/29569434/28822854-da8e8734-76b2-11e7-8baf-482ce09b3678.PNG)

 7.	A new window is opened but the table is not displayed. View Task Manager and see the python.exe task is using large amount of memory. 

![hc 050 3](https://user-images.githubusercontent.com/29569434/28822873-eefda75e-76b2-11e7-9543-d1cd565be75a.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by mzuehlke** [comment]
Limit amount of data to the first 1000 rows

**Comment by HelenClifton** [comment]
Cannot yet see fix in 0.9.0.dev.6. Is it in next release ?

**Comment by mzuehlke** [comment]
Do you still see a crash ?

**Comment by HelenClifton** [comment]
Yes, I was using cate.0.9.0.dev.6, I re-ran the steps described in this issue.
The python.exe process used more and more memory, it got to about 6GB then every application on my machine froze and I had to manually power it off

**Comment by forman** [comment]
Removed `cu_mandatory` because it is implied by  `cu_review`

**Comment by HelenClifton** [comment]
Confirmed fixed in 0.9.0-dev.7. The “Show data in table” is now disabled in this case.
