### ISSUE TITLE
Values persisted in "Download Data Source" window

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#307]
### Expected behavior

Each time the “Download Data Source” window is opened, the values contained in it should be cleared / reset.  (An exception might be the temporal and regional constraints)
See also #308 

### Actual behavior

The following values in the “Download Data Source” window are persisted the next time the window is opened:
•	Time Constraints (if set)
•	Region Constraints (if set)
•	Variable Constraints (if set)
•	Unique ID for the new local data source
•	Data source title

This can have some unwanted effects :
•	Time Constraints which were correct for the old dataset, are now are shown as “out of range” if the new dataset has different temporal coverage.
•	Variables are still selected from the old dataset even if they don’t exist in the new one
•	The default unique ID which is displayed has already been used. So if the user does not change it, the new data is not downloaded and an error message is generated.

(Note: values are persisted also when cate is closed and re-opened)

### Steps to reproduce the problem

 1.	Open GUI

2.	From ESA CCI Open Data Portal list, select esacci.AEROSOL.5-days.L3C.AEX.GOMOS.Envisat.aergom.2-19.r1 then click on “Download and/or open remote dataset”

3.	In the “Download Data Source”, enter:
•	Time constraint: 2011-01-01 to 2012-01-01
•	Region: Lon. from -100 to 100, lat. from -70 to 70
•	Select variables: AEX550 (km-1), altitude (km), latitude (degrees_north), longitude (degrees_east)
•	Check “Download and make local data source”
•	Keep default unique ID: local.AEROSOL.5-days.L3C.AEX.GOMOS.Envisat.aergom.2-19.r1
•	Data source title: “title1”

![hc041 1](https://user-images.githubusercontent.com/29569434/28826086-a8d3004a-76c0-11e7-909d-f4d9d883ef5f.PNG)

4.	Click “Download”.

5.	Now from ESA CCI Open Data Portal list, select esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1 then click on “Download and/or open remote dataset”

6.	In the “Download Data Source”, observe:
•	Time constraint: Now shown as “Out of range”
•	Region: Lon. From -100 to 100, lat. from -70 to 70 (as before)
•	Variable : AEX550, altitude, latitude, longitude (as before, but these variables don’t exist in the Ozone dataset)
•	Unique ID: local.AEROSOL.5-days.L3C.AEX.GOMOS.Envisat.aergom.2-19.r1 (as before, but is now incorrect)
•	Data source title: “title1” (as before)

![hc041 2](https://user-images.githubusercontent.com/29569434/28826108-b8159568-76c0-11e7-825d-1b8ee89c53af.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by forman** [comment]
I agree, an exception should be the temporal and regional constraints for time being. Later we might add drop-down lists from where users can select and reuse recently entered values.

**Comment by HelenClifton** [comment]
Using the steps above with cate.0.9.0.dev.6, 
Variables and data source title are cleared. Unique ID still has value from previous download. 
Unique ID should also be cleared because if the user does not change it, the new data is not downloaded and an error message is generated.
Ticket needs to stay open and be re-assigned.
![capture307](https://user-images.githubusercontent.com/29569434/30168211-a172b04c-93e0-11e7-8871-752e5e24e7b1.PNG)

**Comment by mzuehlke** [comment]
Good catch

**Comment by forman** [comment]
Removed `cu_mandatory` because it is implied by  `cu_review`

**Comment by HelenClifton** [comment]
Using the "steps to reproduce" with cate.0.9.0.dev.7,
Unique ID still has value from previous download (same as in cate.0.9.0.dev.6, see comment above)

**Comment by mzuehlke** [comment]
Please re-test with 1.0.0.dev1

**Comment by HelenClifton** [comment]
Confirmed it is fixed in 1.0.0.dev1. Closing issue.
