### ISSUE TITLE
Temporal / regional / variable constraints are not shown in Details area for dataset

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#314]
### Expected behavior

Downloading and opening a dataset with temporal, regional, and variable constraints.  In the Workspace panel, expect the Details area for the corresponding **open_dataset** workflow step to show the time range, region and variables selected for this dataset.

May have a link to #315

### Actual behavior

The time range, region and variables are displayed as **null** (default value).
note: this also happens when full dataset is downloaded without any time range / region / variable constraints applied. 

### Steps to reproduce the problem

1. In the remote data sources list, select **esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1** and click “download and/or open remote dataset” button
In “Download Data Source” window:
•	Select Time Constraint: 2007-01-01 to 2007-04-01
•	Select Region Constraint: Longititude from -100 to 100, Latitude from -60 to 60
•	Select Variables from the list: cee, cee_corr_unc, cee_prop_unc, cee_std, cee_unc
•	Check “Download and make local data source“
•	Leave the unique identifier as the default value
•	Check the box “Open dataset from local data source“ 
•	Click “Download & Open Local“

![hc054 1](https://user-images.githubusercontent.com/29569434/28932358-1d48096e-7871-11e7-973e-1ce534e69880.PNG)

2. Wait for the loading to complete. 
3. In the Workspace panel, select the new **open_dataset** workflow step then ensure Details is selected. Look at list of Step Inputs and see **null** values.

![hc054 2](https://user-images.githubusercontent.com/29569434/28932396-3da2b6dc-7871-11e7-8b41-cc364b16a40b.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by mzuehlke** [comment]
The `open_dataset` operation has no parameter to limit the time, region, or variables.
These constraints are applied in the `make_local`step.

BUT:

The `make_local` function of the OPD data source does not update the metadata according to the selected constraints:
* date_time
* geospatial boundaries
* variables

**Comment by forman** [comment]
Fixing this requires fixing #287

**Comment by forman** [comment]
Decided to remove `cu_mandatory` label at IRM6.

**Comment by forman** [comment]
In fact, this is only partly fixed by #287.

The issue is fixed for datasets opened from remote services (ODP), either by download or OPeNDAP.  Then, an `open_dataset()` workflow step is inserted with all the user-provided constraints. But if the downloaded  dataset is later on loaded from **local**, the old constraints are of course not visible, because new constraints may apply, which are usually all *None* for local data sources.

Therefore, I'l leave the issue open but move it to MS IRM7.

**Comment by HelenClifton** [comment]
Confirmed fixed in cate-0.9.0.dev7
