### ISSUE TITLE
Opening local dataset: User can select variables which aren't in dataset

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#315]
### Expected behavior

A local dataset is created by downloading a remote data source with variable constraints applied.
The local dataset is then opened. It should only be possible for the user to select variables which exist in the local dataset. 

May have a link to #314

### Actual behavior

In the "Open local dataset" window, the full list of variables from the remote data source is displayed, including those which aren't in the local dataset.  The user can open a resource by selecting any of these.

### Steps to reproduce the problem

1.In the remote data sources list, select **esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1** and click “download and/or open remote dataset” button
 In “Download Data Source” window:
• Select Time Constraint: 2007-01-01 to 2007-04-01
• Select Region Constraint: Longititude from -100 to 100, Latitude from -60 to 60
• Select Variables from the list: **cee, cee_corr_unc, cee_prop_unc, cee_std, cee_unc**
• Check “Download and make local data source“
• Leave the unique identifier as the default value
• Ensure “Open dataset from local data source“ is not selected
• Click “Download & Open Local“

![hc 053 1](https://user-images.githubusercontent.com/29569434/28960639-62102046-78f7-11e7-993b-14246f2f8410.PNG)

2. Wait for download to complete then in the local data sources list, select 
**local.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1** 
Click “Open local dataset” button
In “Open Local Dataset” window:
•	Select Variables constraint and open the list

![hc 053 2](https://user-images.githubusercontent.com/29569434/28960311-f6c83194-78f5-11e7-9e90-1026c66399c1.PNG)
•	See that the full list of variables is displayed even though the dataset has been created in previous step from sub-set of five variables (cee, cee_corr_unc, cee_prop_unc, cee_std, cee_unc)

![hc 053 3](https://user-images.githubusercontent.com/29569434/28960314-f953998a-78f5-11e7-8d03-fc72775d68b3.PNG)

3. Select some variables which are not in the dataset, click OK then "Open Local"

![hc 053 4](https://user-images.githubusercontent.com/29569434/28960322-03cfd3c4-78f6-11e7-81d8-807999a5692c.PNG)

4. Look at Workspace panel. New resource has been created of type Dataset. Details pane indicates that the dataset contains the variables which were selected in the last step

![hc 053 5](https://user-images.githubusercontent.com/29569434/28960647-68342a6c-78f7-11e7-9219-01ad8422b703.PNG)

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by mzuehlke** [comment]
The `make_local` function of the OPD data source does not update the metadata according to the selected constraints:
* date_time
* geospatial boundaries
* variables

**Comment by forman** [comment]
Removed `cu_mandatory` because it is implied by  `cu_review`

**Comment by HelenClifton** [comment]
Confirmed fixed in cate-0.9.0-dev7
