### ISSUE TITLE
Empty resource is created when data are not available

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#317]
### Expected behavior

When opening a local dataset: If a time constraint is selected for which no data are available, a warning should be given to the user and a resource should not be opened.

### Actual behavior

A resource of type **NoneType** is created. This is confusing for the user.

### Steps to reproduce the problem

1.In the remote data sources list, select **esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1** and click “download and/or open remote dataset” button
 In “Download Data Source” window:
• Select Time Constraint: 2007-01-01 to 2007-04-01
• Select Region Constraint: Longititude from -100 to 100, Latitude from -60 to 60
• Select Variables from the list: cee, cee_corr_unc, cee_prop_unc, cee_std, cee_unc
• Check “Download and make local data source“
• Leave the unique identifier as the default value
• Ensure “Open dataset from local data source“ is not selected
• Click “Download & Open Local“

2.Wait for download to complete then in the local data sources list, select
**local.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1**
 Click “Open local dataset” button
 In “Open Local Dataset” window:
• Select Time Constraint: **2007-01-01** to **2007-01-15**
• Click on "Open Local"

![hc 052 1](https://user-images.githubusercontent.com/29569434/28965628-f7f37330-7909-11e7-87ab-9a79171adabd.PNG)

4.Look at Workspace panel. New resource has been created of type NoneType . 

![hc 052 2](https://user-images.githubusercontent.com/29569434/28965638-00cb00ea-790a-11e7-93c9-dbaf7fd42a3b.PNG)

### Specifications 

Cate 0.9.0-dev.4
 Windows 7 Professional

**Comment by mzuehlke** [comment]
See 
* Empty local data sources #269 
* Problem with empty data sources #218

**Comment by kbernat** [comment]
Checked with CLI, Seems to be fixed.

**Comment by mzuehlke** [comment]
The error is still present because `open_datasource` returns `None`.

**Comment by kbernat** [comment]
@mzuehlke , @forman 
what is expected behaviour when user select timerange out for available temporal coverage of product?

**Comment by kbernat** [comment]
#351 should fix it now..

**Comment by mzuehlke** [comment]
Have you tested it ?

**Comment by forman** [comment]
Removed `cu_mandatory` because it is implied by  `cu_review`

**Comment by HelenClifton** [comment]
Still seen in 0.9.0-dev.7, will retest in 1.0.0

**Comment by kbernat** [comment]
Will handle properly when #393 is done.

**Comment by HelenClifton** [comment]
Confirmed it is fixed in cate 1.0.0-dev.2. It gives a warning instead.
