### ISSUE TITLE
Regional subset crossing anti-meridian

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#318]
### Expected behavior

Handling of international date line needs to be discussed with scientists (champion users). Is it a requirement to be able to subset over international date line ?
Once user requirements are known, then need to discuss how this is handled in cate.

### Actual behavior

Currently when region over date line is selected, cate will switch over the longitudes:
start longitude ---> end longitude
end longitude ---> start longitude 
and a region in the opposite side of the globe is selected.

**Comment by JanisGailis** [comment]
@HelenClifton Can you please provide the coordinates used for selection? Cate should handle subsets over international date line.

**Comment by HelenClifton** [comment]
test

**Comment by HelenClifton** [comment]
@JanisGailis Here are two procedures to try

1.	Open GUI

2.	In the remote data sources list, select esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1 and click “download and/or open remote dataset” button
In “Download Data Source” window:
•	Select Time Constraint: 2007-01-01 to 2007-04-01
•	Select Region Constraint: Longitude from 130 to -130, Latitude from -30 to 30
•	Deselect “Download and make local data source“
•	Select “Open dataset from remote (in memory, via OPeNDAP)“ 
•	Click “Open Remote“


![hc 055 1](https://user-images.githubusercontent.com/29569434/29116726-b39d68ec-7cf3-11e7-8e2f-612c5b5ceaaa.PNG)


3.	Inspect World view

and

1.	Open GUI

2.	In the remote data sources list, select esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1 and click “download and/or open remote dataset” button
•	In “Download Data Source” window:
•	Select Time Constraint: 2007-01-01 to 2007-03-01
•	Leave Region Constraint and Variable Constraint unselected
•	Select “Download and make local data source”
•	Leave unique ID as default value
•	Click “Download“

![hc 055 2](https://user-images.githubusercontent.com/29569434/29116540-02220190-7cf3-11e7-9b47-7c9f4b2fe80a.PNG)


2.	Wait for download to complete then click “Open Local Dataset”

3.	In “Open Local Dataset” window:
•	Leave Time Constraint unselected
•	Select Region Constraint 20 to -20, Latitude from -30 to 30
•	Leave Variable Constraint unselected
•	Click “Open Local”

![hc 055 3](https://user-images.githubusercontent.com/29569434/29116547-05beefca-7cf3-11e7-908e-27d8f0635ed8.PNG)

4.	Inspect World view

**Comment by mzuehlke** [comment]
The `make_local` function used it own subset code which seems to not handle the international dateline correctly. 
Maybe @JanisGailis  and @kbernat can harmonize that.

**Comment by HerzogStephan** [comment]
Maybe I miss understood something - But as every data-point has the same world-time (UTC) there should not be an issue with the international date line.

**Comment by forman** [comment]
@HerzogStephan the issue is the anti-meridian where +180 and -180 degrees meet. It is *not* about the international dateline and associated timing issues.

**Comment by forman** [comment]
`subset_spatial` and `make_local` *should* use the same subset code and both *shall* handle the anti-meridian correctly, that is when `west > east` and 'Lon from' is greater than `Lon to`.

**Comment by JanisGailis** [comment]
Note that spatial subset implementation has now been refactored out in util/opimpl.py and can be re-used if suitable.
