### ISSUE TITLE
Data sources should report availability

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#337]
### Expected behavior

Data sources should have a state property that represents the current availability, e.g.:
* DOWNLOADING
* CANCELLED
* ERROR
* READY

### Actual behavior

New (local) data source are immediately added to the (local) data store and appear available to any UI.

### Specifications 

Cate 0.9 dev5

**Comment by kbernat** [comment]
@forman 
If it's not a problem I can provide some workaround quickly - I can add newly created data source to the data store "registry" only after download is complete.

**Comment by kbernat** [comment]
The data source itself will be stored on disk and unique name is locked, so there is no way to add it twice.

**Comment by forman** [comment]
Added blocker because it is (one) reason for #317 which is a `cu_mandatory`.
