### ISSUE TITLE
Either temporal_aggregation or LTA fails

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate#340]
### Expected behavior

[Happy Path](https://github.com/CCI-Tools/cate-core/blob/master/scripts/uc06.sh) for UC06 should still work when one selects another period, but still uses the same dataset as in the happy path.

### Actual behavior

At some point from the temporal_aggregation to the LTA cate runs into an error.

### Steps to reproduce the problem

Please stick to the shell-script outlined [here](https://github.com/CCI-Tools/cate-e2e/blob/master/scripts/UC6/UC06_S2_v001.sh).

The LTA step returns:
"Long term average operation expects a monthly dataset running temporal aggregation on this dataset beforehand may help."
But within the script a temporal_aggregation step is calculated before.

### Specifications 

CLI, Linux, cate-0.9.0_dev5

**Comment by HelenClifton** [comment]
Information @HerzogStephan @JanisGailis @forman Same is seen when running the same steps on the GUI (Windows machine). 
![capture lta 1](https://user-images.githubusercontent.com/29569434/30114964-4016eedc-9311-11e7-82ef-14f672ed6060.PNG)

See link below for the traceback:
[issue340.txt](https://github.com/CCI-Tools/cate-core/files/1281266/issue340.txt)
