### ISSUE TITLE
Time constraint is being ignored for data download if entered in wrong format

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#345]
### Expected behavior

Downloading soil moisture dataset and applying time constraint

### Actual behavior

Time constraint is ignored
May be because "From" and "To" are no longer separate fields in "Download Data Source" window

### Steps to reproduce the problem

1. Download Data Source as below:

![time](https://user-images.githubusercontent.com/29569434/30121481-af852a24-9323-11e7-80e1-88468a931b4e.PNG)

2. Look in local data store, see files from 1978 onwards are being saved 

### Specifications 

cate-0.9.0.dev6
Windows 7 Professional

**Comment by mzuehlke** [comment]
Hi Helen,
before entering a date range in the input field the hint shows the format as `YYYY-MM-DD,YYYY-MM-DD`.
Maybe I should format the text below the input field in a similar format.

**Comment by HelenClifton** [comment]
@mzuehlke Hi, thanks for this.
When I put the time range in the correct format, the time constraints are applied correctly.
It would also be a good idea, if the format is incorrect, to warn the user, rather than ignoring the input and downloading the entire dataset (which can take several hours)

**Comment by mzuehlke** [comment]
Yes, you are right. I'm already looking into the missing validation.

**Comment by forman** [comment]
@mzuehlke 
> Maybe I should format the text below the input field in a similar format.
Definitely not a maybe. I'll fix it.

**Comment by forman** [comment]
Will be closed with #374

**Comment by HelenClifton** [comment]
Confirmed fixed in cate-1.0.0-dev.1. Format is now validated.
