### ISSUE TITLE
Hide problematic ODP data sources

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#368]
### Expected behavior

Cate Desktop should not list ODP data sources in **DATA SOURCES** panel which are known to produce problems in the software. For example

* cannot be opened without error (`xarray` raises exceptions, e.g. due to problems with  time units);
* opening it produces a resource of `NoneType` rather than `Dataset` or `DataFrame`;
* cannot be displayed on 3D globe, but should be representable as image;
* takes way too long to display and/or requires too much CPU/memory in doing so.

### Actual behavior

All data source are shown.

### Steps to reproduce the problem

1. In **DATA SOURCES** panel, choose *ESA Open Data Portal* data store and search for `OC r2`.
2. Download
3. Select any variable --> Nothing is displayed on 3D globe

### Specifications 

0.9.0.dev7

**Comment by forman** [comment]
Ed: maintain a whitelist of supported ODP data sources rather than a blacklist

**Comment by forman** [comment]
Reopened to let users review it.

**Comment by mzuehlke** [comment]
Has been implemented with https://github.com/CCI-Tools/cate/commit/d6c43fb1a9065589dab7cf310fc6b71ec917ff51
Must be reviewed before it can be closed

**Comment by HerzogStephan** [comment]
I currently test it with "1.0.0.dev2". I contact you with an update Monday morning.
