### ISSUE TITLE
Failed/incomplete downloads still appear in local data sources

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#375]
### Expected behavior

Just got a `connection timeout` during a download of a large data source (the OZONE one from #374). I expected the failed/incomplete download *not* to appear in my local data sources next time I start Cate.

### Actual behavior

The data source appears.

![image](https://user-images.githubusercontent.com/206773/30638159-c0bbd32e-9dfa-11e7-994c-3ccde53fe49d.png)

Note that the `*.lock*` file could tell that a download is ongoing. It could also contain status incl. progress and error information about the download.

The issue is closely related to #337.

### Specifications 

Cate 0.9.0.dev7

**Comment by mzuehlke** [comment]
Hi @kbernat 

When the user cancels the download you remove all files, but if an error occurs while downloading all files already downloaded remain on disk. Is this intended?

https://github.com/CCI-Tools/cate/blob/b519f2101ef013b0c2f6c91a5eef7a9ab75e38e7/cate/ds/esa_cci_odp.py#L1009-L1017

**Comment by kbernat** [comment]
@mzuehlke yes, it's our "resume" feature :)

**Comment by kbernat** [comment]
@mzuehlke  we may think about asking user if incomplete data should be kept or not..

**Comment by forman** [comment]
I suggest that a resume should only be possible/required on external errors, e.g. `timeout` and `IOError`, not  on any (possibly developer) error that might occur in `make_local`, see #393
