### ISSUE TITLE
LTA retains year representation

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate#387]
### Expected behavior

When useing the *long_term_average* operation and use the *plot* operation afterwards I expect cate to switch from "YYYY-MM" timestamps to "MM". (And maybe report about the considered timespan somewhere in the plot.)

### Actual behavior

Cate keeps the years from the first year in the considered timespan for every displayed time-label (see screenshot for clarity). 

Shows the long-term-average for the years 2006-2009:
![cate_issuetracker_008](https://user-images.githubusercontent.com/25434328/30688574-d6291f04-9ebe-11e7-9076-37e7f4871799.png)

### Steps to reproduce the problem

_Please stick to the [UC2 Happy Path](https://github.com/CCI-Tools/cate-core/blob/master/scripts/uc02.sh)_

### Specifications

Cate dev6, linux

**Comment by forman** [comment]
Interesting problem. A dataset resulting from LTA should not get a "normal" time dimension. Is there some (CF) convention for LTAs e.g. climatologies?

**Comment by JanisGailis** [comment]
@forman Yes there is:
http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#climatological-statistics

And the dataset produced by LTA operation corresponds to the conventions. It adds the 'climatology_bounds' variable to the dataset and ties it to 'time' variable as 'climatology'. CF conventions advice against using 'weird' years to denote a climatology (e.g. 0), the official suggestion is to use dates that are in a way 'representative' of the period over which the climatology was formed (see examples in the above URL). For LTA I have elected to use 'beginning of climatology period' as the date to use.

**Comment by JanisGailis** [comment]
Closing this, as behavior is according to CF conventions
