### ISSUE TITLE
CLI desktop shortcut does not appear

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#398]
### Expected behavior

CLI desktop shortcut should appear on Ubuntu Unity.

### Actual behavior

CLI desktop shortcut does not appear on Ubuntu Unity.

### Steps to reproduce the problem

Install Cate Core on Ubuntu Unity.

### Specifications 

0.9.0.dev7 on Ubuntu Unity

**Comment by mzuehlke** [comment]
1. Installed Cate Core
2. Found the "cate CLI" desktop entry.
3. Started Cate Desktop from AppImage and confirmed to add desktop entry
4. Found the "cate desktop" desktop entry.

I did this on Ubuntu 16.04 in virtualbox. Using Unity (default with ubuntu)

**Comment by forman** [comment]
Therefore we close it.
