### ISSUE TITLE
Overwritten 'Time constraints' in consecutive download attempts 

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#403]
_From @HerzogStephan on August 15, 2017 7:22_

### Actual behavior

For the first attempt downloading an ODP-dataset in a GUI-session and with 'Time constraint' enabled - one sees the available timespan for the selected ODP dataset. But for the following download attempts the 'Time constraint' fields, that normally show the available timespan, are overwritten by the values given in the previous download. ('Download Data Source'-Panel)

(Only reproducible when actually downloading a dataset!)

### Expected behavior

For consecutive download attempts the user should see the actual timespan for every ODP dataset. (Or at least should have a sort of 'Default'-button to reset all settings in the 'Download Data Source'-panel).

### Steps to reproduce the problem

1. Select an ODP dataset
2. Press 'Download and/or open remote dataset'
3. Select 'Time constraint' in the 'Download Data Source' Panel
4. Press 'Download'-Button in the same Panel.

![20170815catedesktop_009](https://user-images.githubusercontent.com/25434328/29305856-176c5d14-819b-11e7-9472-ea340d2bedfa.png)

5. Select a different ODP dataset
6. Press 'Download and/or open remote dataset'
7. Select 'Time constraint' in the 'Download Data Source' Panel
--> Recognize that 'Time constraints' were stored.

![20170815catedesktop_008](https://user-images.githubusercontent.com/25434328/29305826-fe37cef0-819a-11e7-8d44-07c491bb1d2f.png)

### Comment

Maybe I missed a GUI-functionality that does this thing.

### Specifications

Cate 0.9.0.dev4 

_Copied from original issue: CCI-Tools/cate-desktop#37_

**Comment by forman** [comment]
@HerzogStephan could you please verify, if this still applies?

**Comment by HerzogStephan** [comment]
Fixed. Can be closed. I cannot close it somehow.
