### ISSUE TITLE
"Remove local data source" does not always work

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#410]
_From @HelenClifton on June 29, 2017 13:42_

### Expected behaviour

Selected "Remove local data source" then "Remove data files from local disk".
Expected cate to remove the data source from the list of local data sources and remove the files from the local disk.

### Actual behavior

The data source is not removed from list of local data sources.
The files remain on the local disk.
Error message appears.

Note: The problem may be because the local data source was added from the Desktop and not the folder  C:\Users\HClifton\.cate\data_stores\local.
If this is the case, then cate should should only allow users to open data sources from the above folder and not anywhere else.

### Steps to reproduce problem

1. Create a new folder on the desktop called myfolder with some test data
2. In cate GUI, data sources pane,  select local data store from the drop down list
3. Click "Add local new data source" and select myfolder

![capture1](https://user-images.githubusercontent.com/29569434/27689693-ed6d7bee-5cd6-11e7-9787-c25e030ae3b6.PNG)

4. Click "Add"
5. Click on new dataset then "Remove local data source" 

![capture2](https://user-images.githubusercontent.com/29569434/27689820-62f619a2-5cd7-11e7-8f3d-f9875de49bcc.PNG)

6. Select "Remove data files from local disk", click "Remove"
7. Observe that it is not removed from list of local data sources
8. Observe error message, it cannot find the path specified

![capture3](https://user-images.githubusercontent.com/29569434/27689914-b79727ee-5cd7-11e7-9bad-d800b922f600.PNG)

### Specifications 

cate 0.8.0-rc6
 Internet Explorer 11
 Windows 7 Professional

_Copied from original issue: CCI-Tools/cate-desktop#28_

**Comment by kbernat** [comment]
@forman should we remove files from disk if Data Source is pattern based? Files are not being stored within local data store location.

**Comment by forman** [comment]
No, please only files that Cate has written.

**Comment by HelenClifton** [comment]
Confirmed it is fixed in cate 1.0.0-dev.2
