### ISSUE TITLE
"Save Workspace As" does not work

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#419]
_From @HelenClifton on June 20, 2017 11:10_

When File->Save Workspace As is selected, there isn't a way to enter the name for the new workspace. 
![capture](https://user-images.githubusercontent.com/29569434/27330397-21291e3e-55b1-11e7-9ace-205d76c72451.PNG)

If "Select" is clicked, an error message is shown

![capture](https://user-images.githubusercontent.com/29569434/27330433-468b67fe-55b1-11e7-9700-10cc0d5a39dd.PNG)

_Copied from original issue: CCI-Tools/cate-desktop#14_

**Comment by forman** [comment]
Yes, a known problem. To get around it: create an empty directory first and then select its name. 

We actually need a directory chooser.

**Comment by forman** [comment]
@HelenClifton unfortunately there is currently no real fix for that, because the Electron platform does not allow us selecting non-existing directories. See https://github.com/electron/electron/issues/9411.

To all: are there any suggestions how to proceed?

**Comment by HelenClifton** [comment]
@forman : The user probably will not know in advance that they need to create a new folder.
So, the suggestion is: the user navigates to the workspace home (the folder where the new workspace will be) and then a pop up appears asking the user to enter a name for the new workspace.

**Comment by forman** [comment]
That sound reasonable. What about a dialog that looks like this:

    +------------------------------------------------------------------+
    |    New Workspace                                               X |
    +------------------------------------------------------------------+
    |                                                                  |
    |    Parent directory:                                             |
    |                                                        +-----+   |
    |    ________________________________________________    | ... |   |
    |                                                        +-----+   |
    |                                                                  |
    |    Workspace name:                                               |
    |                                                                  |
    |    ________________________________________________              |
    |                                                                  |
    |                                                                  |
    |                                   +--------+        +--------+   |
    |                                   |   OK   |        | Cancel |   |
    |                                   +--------+        +--------+   |
    |                                                                  |
    +------------------------------------------------------------------+

**Comment by HelenClifton** [comment]
Looks fine to me !

**Comment by forman** [comment]
Fixed in 1.0.1 as proposed.

**Comment by HelenClifton** [comment]
@forman Tested with cate-2.2.0-dev.1 - not quite as expected - please could you take a look ?
1. File->New Workspace
2. Select an empty folder as the parent folder, enter a new workspace name
![capture1](https://user-images.githubusercontent.com/29569434/37206229-ba016948-238f-11e8-9a2a-c452d539b3af.PNG)
3. Workspace is created. Then select "Download Data Source"
![capture2](https://user-images.githubusercontent.com/29569434/37206256-d6233cc8-238f-11e8-9ac4-e911d49b64af.PNG)
4. Click Download and see error:
![capture3](https://user-images.githubusercontent.com/29569434/37206277-e6bf8d8e-238f-11e8-9818-5ddbb0324987.PNG)
Traceback is here: [Traceback.txt](https://github.com/CCI-Tools/cate/files/1796739/Traceback.txt)

**Comment by forman** [comment]
Does the `UC09` folder exist?

**Comment by HelenClifton** [comment]
@forman If I create the UC09 folder first, then it's fine.
Later on if I choose File->Save Workspace As, it will create a new sub-folder within the parent directory, as expected.

**Comment by forman** [comment]
Strange. It works for me, even if the workspace folder does not exist. But the parent must exist.
