### ISSUE TITLE
Too many possible operations displayed

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#420]
_From @HelenClifton on June 20, 2017 10:48_

**Actual behaviour**
Under Operations, on left hand side of GUI,  some of the operations shown are only relevant for the CLI not the GUI, because they are done behind the scenes in the GUI. 

**Expected behaviour**
Only show operations in the list which  are  relevant for the Desktop interface.
 
**Specification**
 cate-desktop 0.8.0-rc5

_Copied from original issue: CCI-Tools/cate-desktop#10_

**Comment by forman** [comment]
Not sure what you mean. Which operations exactly? In fact, there shouldn't be any GUI-specific operations at all.

**Comment by forman** [comment]
@HelenClifton is this still relevant or can we close it?

**Comment by HelenClifton** [comment]
This can be closed.
