### ISSUE TITLE
Unhelpful message to user when remote data source cannot be opened

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#421]
_From @HelenClifton on June 20, 2017 10:41_

Actual behaviour
If a remote data source cannot be opened, the error pop-up which appears does not tell the user what the problem is

![capture](https://user-images.githubusercontent.com/29569434/27329405-5b208a22-55ad-11e7-907c-e9f1273ab8e6.PNG)

Expected behaviour
Pop-up should say something like "Cannot open remote data source" and maybe give suggestions for things to check, e.g. is there an internet connection

Specification
 cate-desktop 0.8.0-rc5

_Copied from original issue: CCI-Tools/cate-desktop#9_

**Comment by forman** [comment]
Addressed by #393

**Comment by HelenClifton** [comment]
Confirmed fixed in cate 1.0.0-dev1
![capture1](https://user-images.githubusercontent.com/29569434/31268458-450f26aa-aa74-11e7-9f57-0599aa119a42.PNG)
Can be closed.
