### ISSUE TITLE
Rename this repo as "cate"

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#425]
I'd like to rename this repository from `cate-core` to just `cate` for the following reason:

1. It represents the entire project, *including* its core but not necessarily *being* the core. `cate.core` is only of one many `cate` Python sub-packages;
2. At IRM7 we agreed that there should be only one project issue tracker, and it is the one of this repository;
3. All Cate documentation in this repository including the one for Cate Desktop. ReadTheDocs still is named `ect-core` and resetting it to `cate` make things easier to follow;
4. Renaming a repository doesn't usually cause problems at all, GitHub will delegate all old links correctly. Only the ReadTheDocs configuration must be regenerated.

Checklist:

- [x] Rename this repo
- [x] Rename this repo's contents
- [x] Rename in `cate-conda` repo
- [x] Rename in `cate-desktop` repo
- [x] Rename in `cate-installer` repo
- [x] Rename in Travis CI
- [x] Rename in AppVeyor
- [x] Rename in RTD
- [x] Rename Cate's Python environment from `cate` to `cate-env` to minimize confusion

**Comment by kbernat** [comment]
Do you need some help/plan any actions for particular devs?

**Comment by forman** [comment]
No, I just want your approval or veto plus reason why not.

**Comment by JanisGailis** [comment]
Ah, approval then from my side

**Comment by mzuehlke** [comment]
Go for it.

**Comment by forman** [comment]
I'll do it later tonight to minimize impacts.

**Comment by forman** [comment]
Done.
