### ISSUE TITLE
Build fails with Dask 0.15.3

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate#427]
It seems that groupby on Xarray datasets does not work with Dask 0.15.3, hence coregistration which relies on it fails.

```python
import xarray as xr
import numpy as np
import dask


def plus_one(da):
    return da + 1


print(xr.__version__)
print(dask.__version__)

ds = xr.Dataset({
    'first': (['time', 'lat', 'lon'], np.array([np.eye(4, 8), np.eye(4, 8)])),
    'second': (['time', 'lat', 'lon'], np.array([np.eye(4, 8), np.eye(4, 8)])),
    'lat': np.linspace(-67.5, 67.5, 4),
    'lon': np.linspace(-157.5, 157.5, 8),
    'time': np.array([1, 2])}).chunk(chunks={'lat': 2, 'lon': 4})

ds_new = ds.groupby('time').apply(plus_one)
```

**Comment by JanisGailis** [comment]
I opened an Issue in xarray repository regarding this:
https://github.com/pydata/xarray/issues/1592

**Comment by forman** [comment]
https://github.com/CCI-Tools/cate/blob/master/environment.yml#L14

**Comment by JanisGailis** [comment]
The issue seems to be fixed and merged already in Dask:
https://github.com/dask/dask/issues/2718

We should monitor when 0.15.4 comes out and then bump the version and close this.

**Comment by mzuehlke** [comment]
Ok, `dask` 0.15.4 is out, which includes the fix. So we can remove to `dask <0.15.3` limitation after the release is out:
https://github.com/dask/dask/releases/tag/0.15.4
http://dask.pydata.org/en/latest/changelog.html
