### ISSUE TITLE
Issue with updating cate version on Windows

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#428]
### Expected behavior

I have an existing cate version 0.9.0.dev6 installed on my machine . Expect that I can update this to cate-0.9.0.dev7 without having to remove all the files.

### Actual behavior

When cate core installer is run there is an error and installation cannot proceed (unless the folder selection is changed)

![install1](https://user-images.githubusercontent.com/29569434/30856374-1277bec6-a2b0-11e7-82d3-394037e9c8c7.PNG)

![install2](https://user-images.githubusercontent.com/29569434/30856384-18c4ebe6-a2b0-11e7-98b4-5134d7fbecec.PNG)

### Steps to reproduce the problem

1. Ensure previous cate version is installed on machine 
2. Download cate-0.9.0.dev7-Windows-x86_64 
3. Run the application until "choose install location" stage is reached
4. Keep the destination folder as the default and click "Next"

### Specifications 

Windows 7 Professional

**Comment by forman** [comment]
@HelenClifton I'm sorry to say that we currently can't change this behavior as the installer software doesn't allow for installation into non-empty directories, I fear, we cannot easily fix it.

What you *can* do is the following: Don't use the installer and just update an old Cate in its existing Python environment using the Cate CLI (from start menu). In the shell, type:

    > conda update -c conda-forge cate
  
Then verify

    > cate --version

**Comment by forman** [comment]
No, wait! The above will update to the very latest version! Use instead

    > conda install -c ccitools -c conda-forge cate-cli=0.9.0.dev7

To install a specific version.

**Comment by forman** [comment]
Should not apply anymore as we don't require cate-core installers, see #523
