### ISSUE TITLE
List only data sources tested by the champion users

### ISSUE THREAD

**Issue by thomas-eldridge** [CCI-Tools/cate#435]
Working on UC6, attempted to query dataset search bar with 'ss[t]', 'sea su[rface temperature]', 'tem[perature]', 'soi[l moisture]; all queries failed i.e. returned no results from beginning of square bracket.

The number of datasets available for use in dev.7 when no queries have been entered intot the search bar is 52. I think this is significantly less than were available for dev.6 and earlier. Is there a reason for this, or has my install malfunctioned? Have others encountered this problem?

**Comment by mzuehlke** [comment]
With #368 we have put in filter to hide data sources that lead to problems

https://github.com/CCI-Tools/cate/blob/83f9b1da8004a1adaea48c3037b1f1baefee76b8/cate/conf/template.py#L41-L47

Maybe the exclusion of **all** daly products is too strict.

**Comment by forman** [comment]
@thomas-eldridge I've informed the team about what I did before the 0.9.0.dev7 release and it is just an initial suggestion / demonstration of how inclusion/exclusion of data sources works. The actual includes/excludes should come from you users and will be finalized before the v1.0 release.  I think, @HerzogStephan is currently working on that.

**Comment by forman** [comment]
The justification for the includes/excludes feature comes from #368.

**Comment by HelenClifton** [comment]
The absence of these datasets means that happy paths for use cases #6 and #2 cannot be run in their current form

**Comment by forman** [comment]
They are not absent. Please comment out `excluded_data_sources` as described above or set it to an empty list. Afaik, champion users are working on a consolidation of the `included_data_sources` / `excluded_data_sources` settings for the 1.0. You may ask @HerzogStephan for the current state.
