### ISSUE TITLE
cate 0.9.0-dev7 OS X version installation error

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#438]
### Expected behavior

Expected cate to install on mac

### Actual behavior

There was an installation error when installing cate core

![cate core dev7 installation](https://user-images.githubusercontent.com/29569434/31004978-9d80a178-a4ee-11e7-9331-4483baf3708a.jpg)

### Steps to reproduce the problem

In terminal type 
**cd Desktop
bash cate-0.9.0.dev7-MacOSX-x86_64.sh** 

Accept the license.

### Further info

I tried installing python 3.6 miniconda and this was successful

![python 3 6 miniconda installation](https://user-images.githubusercontent.com/29569434/31005130-4a90f19c-a4ef-11e7-878a-5bd0c130c91e.jpg)

### Specifications 

![mac about 1](https://user-images.githubusercontent.com/29569434/31005173-84df4c72-a4ef-11e7-9af1-968577b02e6e.jpg)

![mac about 2](https://user-images.githubusercontent.com/29569434/31005185-8bad01c0-a4ef-11e7-9b4b-696869411ad1.jpg)

**Comment by forman** [comment]
@HelenClifton Cannot reproduce with OS X Yosemite 10.10.5 where both Cate and Cate Desktop run as expected. Your Mac's OS seems quite outdated. Is it possible to update it?

**Comment by mzuehlke** [comment]
We could reproduce the error with another OS x machine running 10.9.5.
This version is the oldest supported by Annaconda.

**Comment by mzuehlke** [comment]
Taking python from the default channel by providing a full URL gives use 10.9 compatibility.

**Comment by HelenClifton** [comment]
Confirmed fixed. Have successfully installed cate 1.0.0 on the Mac running OS X 10.9.5.

**Comment by forman** [comment]
Yeaaah!
