### ISSUE TITLE
Use Case #9 happy path - pearson correlation fails

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#440]
### Expected behavior

Ran the use case#9 happy path using the GUI.

### Actual behavior

Pearson correlation failed
![pearson1](https://user-images.githubusercontent.com/29569434/31006452-9e82642a-a4f4-11e7-96ce-d7db917f0de4.PNG)
Traceback:
[UC9 happy path traceback.txt](https://github.com/CCI-Tools/cate/files/1343533/UC9.happy.path.traceback.txt)

### Steps to reproduce the problem
See:
[steps to reproduce.docx](https://github.com/CCI-Tools/cate/files/1343604/steps.to.reproduce.docx)

### Specifications 

cate-0.9.0-dev.7
Windows 7 Professional

**Comment by HelenClifton** [comment]
#309 is similar. It may or may not be related.

**Comment by JanisGailis** [comment]
The CLI Happy Path script for UC09 runs as expected on Linux both from current master (1.0.0.dev1) and from 0.9.dev7 tag.

My guess is that somehow when the time range in the GUI is selected, one end is excluded from it, while from the CLI it is inclusive. This would explain why pearson_correlation fails with that message.

**Comment by JanisGailis** [comment]
I disagree with the ops label. The CLI happy paths are working as expected, hence, I don't think the problem is in ops. I will be able to do some debugging of this late on Monday, as I'm travelling for most of it.

**Comment by JanisGailis** [comment]
I can not reproduce this on the GUI of Cate 0.9.dev7. I followed the steps in the document and successfully created the correlation dataset.

**Comment by kbernat** [comment]
Couldn't reproduce either. Used core and gui from git-master branch (1.0.0.dev1)

**Comment by HelenClifton** [comment]
Tried this with cate 1.0.0-dev2 and could not reproduce.
This can be closed.

**Comment by HelenClifton** [comment]
@forman, @mzuehlke, @JanisGailis, @kbernat : It's back in cate-2.0.0-dev.1.
Traceback is here 
[issue440_traceback.txt](https://github.com/CCI-Tools/cate/files/1797096/issue440_traceback.txt)
Steps to reproduce: 
[issue440_steps_to_reproduce.docx](https://github.com/CCI-Tools/cate/files/1797097/issue440_steps_to_reproduce.docx)

**Comment by papesci** [comment]
Dear All, i have executed all the steps successfully  on a Linux machine (ubuntu). 
Please find attached the workspace
[UC9.tar.gz](https://github.com/CCI-Tools/cate/files/1797497/UC9.tar.gz)

**Comment by HelenClifton** [comment]
@forman, @mzuehlke @JanisGailis @kbernat OK... confirmed that it was operator error ...
I'd set end time constraint to 2007-03-01 instead of 2007-03-31
This can be closed again :)
