### ISSUE TITLE
Use Case #6 happy path - temporal aggregation on sst dataset fails

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#443]
### Expected behavior

Ran use case #6 happy path using GUI

### Actual behaviour
When applying temporal_aggregation operation to SST dataset, there was an error:
![sst temporal aggregation](https://user-images.githubusercontent.com/29569434/31018782-2e1ec8fa-a525-11e7-86f2-f67e00c44155.PNG)

The error message looks similar to the one reported in #441 

Traceback:
[sst temporal aggregation traceback.txt](https://github.com/CCI-Tools/cate/files/1344540/sst.temporal.aggregation.traceback.txt)

### Steps to reproduce the problem

See:
[steps to reproduce.docx](https://github.com/CCI-Tools/cate/files/1344548/steps.to.reproduce.docx)

### Specifications 
cate-0.9.0-dev.7
Windows 7 Professional

**Comment by JanisGailis** [comment]
The CLI happy path script for UC2 runs as expected on Linux both from the current master, as well as the dev7 tag.

See also #441

**Comment by JanisGailis** [comment]
I disagree with the ops label. The CLI happy paths are working as expected, hence, I don't think the problem is in ops.

**Comment by HelenClifton** [comment]
Confirmed fixed in cate 1.0.0-dev.3
