### ISSUE TITLE
Basemap fails to load rendering Cesium globe invisible

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate#448]
### Expected behavior

When opening the Cate GUI from a newly installed Cate installation, the Cesium globe should appear.

### Actual behavior

The globe is there, but is invisible because of this error in the developer console:

An error occurred in "BingMapsImageryProvider": An error occurred while accessing http://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?incl=ImageryProviders&key=AnCcpOxnAAgq-KyFcczSZYZ_iFvCOmWl0Mx-6QzQ_rzMtpgxZrPZZNxa8_9ZNXci.

![image](https://user-images.githubusercontent.com/9655353/31126216-47a73d42-a84b-11e7-83f2-96430696a280.png)

### Steps to reproduce the problem

I just uninstalled Cate 0.9.dev6 (both core and GUI) and installed Cate 0.9.dev7. When opening it up, I had no Globe. I think I saw this once before with Cate 0.9.dev6 as well.

### Specifications 

Windows 10, Cate 0.9.dev7 installed with installers

**Comment by forman** [comment]
Seems that Bing service wasn't available at that time.
We should catch the error and fall back to a static map.
