### ISSUE TITLE
Cate-desktop build fails on Ubuntu 17.04

### ISSUE THREAD

**Issue by kbernat** [CCI-Tools/cate#450]
### Expected behavior

Build and Install cate-desktop without errors

### Actual behavior

`npm install` returns error

npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.7.1 install script 'node ./download-chromedriver.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download-chromedriver.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dev/Projects/CCI-Tools/cate-desktop/npm-debug.log

### Steps to reproduce the problem

> apt install npm

Follow the instuction how to build and install cate-desktop

### Specifications 

ubuntu 17.04
fresh install of node.js

**Comment by forman** [comment]
Please use Node LTS version. Updated README accordingly.
