### ISSUE TITLE
Missing static background map

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#453]
### Expected behavior

When Cate Desktop is in offline-mode (File / Preferences / Force offline mode) a static background map should be displayed (low-res Natural Earth 2.0). 

This only occurs in the installed version. When run from sources everything works as expected.

### Actual behavior

The static map isn't displayed. Instead nothing is shown (see #448). 
The reason for this is that the static resources of the map are not packaged in the Cate's `setup.py`.

### Steps to reproduce the problem

In the installed Cate Desktop:

1. Check File / Preferences / Force offline mode
2. Restart Cate Desktop

### Specifications 

Cate / Cate Desktop 1.0.0.dev1

**Comment by mzuehlke** [comment]
Fixed by https://github.com/CCI-Tools/cate/commit/31442549198ee37d4e8b210aabc11ae4eeadfe24
