### ISSUE TITLE
Use Case #9 Happy Path - download times out

### ISSUE THREAD

**Issue by MartinMonkos** [CCI-Tools/cate#454]
### Expected behavior

Make local of "esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1" and "esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1" dataset as given in UC9 happy path.

### Actual behavior

Make local fails and returns: "Copying remote datasource failed, timed out"

### Steps to reproduce the problem
_GUI:_
1. Select "ESA CCI Open Data Portal" within the "DATA SOURCES"-Panel.
2. Search for "esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1" and click on the "Download and/or open remote dataset"-button
3. Select the time constraint and local data source identifier as in UC9 happy path:
Time constraint: "2007-01-01,2007-03-21"
Unique identifier: "local.CLOUD_2007"
4. Press "Download & Open Local" - Button

_CLI:_

Rerun [UC9-Happy Path](https://github.com/CCI-Tools/cate/blob/master/scripts/uc09.sh) and delete the previously loaded datasets. 
(Same for: "'esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1")

I switched between the 0.9.0.dev6, 0.9.0.dev7 and 1.0.0.dev1 and the time out occurs in every version.

### Question:
Is this problem due to the ODP or is there a change through out the dev-versions of cate?

### Specifications 
Linux, cate-1.0.0dev1

**Comment by MartinMonkos** [comment]
In addition: While testing the Happy Paths yesterday I was able to download via UC2 using the following line in CLI:

`cate ds copy esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1 --name CLOUD_2006_2009_region_7_48_10_52 --time '2006-01-01,2009-12-31' --region '7,48,10,52' --vars 'cfc'`

This is very wired as it is the same dataset, but with different parameters.

### Specifications
Using 1.0.0.dev1 and linux

**Comment by mzuehlke** [comment]
See #376
