### ISSUE TITLE
Use Case #6 Happy Path - invalid indexing operation on netCDF4.Variable object 

### ISSUE THREAD

**Issue by MartinMonkos** [CCI-Tools/cate#455]
### Expected behavior

Make local of "esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multiplatform.COMBINED.03-2.r1" dataset as given in UC6 happy path.

### Actual behavior

Make local fails and returns: "The indexing operation you are attempting to perform is not valid on netCDF4.Variable object. Try loading your data into memory first by calling .load()."

### Steps to reproduce the problem

_GUI_ :

1. Select "ESA CCI Open Data Portal" within the "DATA SOURCES"-Panel.
2. Search for "esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multiplatform.COMBINED.03-2.r1" and click on the "Download and/or open remote dataset"-button
3. Select the time constraint and local data source identifier as in UC6 happy path:
    Time constraint: "2007-01-01,2007-03-21"
    Region constraint: "72,8,85,17"
    Unique identifier: "local.SOIL_2007"
    Press "Download & Open Local" - Button

_CLI_:

Rerun UC6-Happy Path and delete the previously loaded datasets.

#### Question:

Is this problem due to the ODP or is there a change through out the dev-versions of cate?

### Specifications

Linux, cate-1.0.0dev1

**Comment by mzuehlke** [comment]
esacci.SOILMOISTURE is not working, because of #444
