### ISSUE TITLE
Cloud dataset is not displayed on 3D globe in some circumstances

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#458]
### Expected behavior

Opened Aerosol dataset into memory
Opened Cloud dataset into memory.
Expected to be able to display cloud dataset on 3D globe.

### Actual behaviour

When the cloud dataset was selected on workspace panel, then Layers panel was selected, it said the dataset was "non geospatial"
However when cate is restarted and only the Cloud dataset is loaded into memory, the problem doesn't occur.
The same issue is seen when the two datasets are downloaded locally and then opened.

### Steps to reproduce the problem

[Steps to reproduce.docx](https://github.com/CCI-Tools/cate/files/1363136/Steps.to.reproduce.docx)

### Specifications 

Windows 7 professional
Cate 1.0.0.dev.2

**Comment by mzuehlke** [comment]
I can not open the  `esacci.AEROSOL.5-days.L3C.AEX.GOMOS.Envisat.aergom.2-19.r1` data source. It is also not on the white list provided by @HerzogStephan . Maybe for that reason.
Can you display this aerosol data source alone ?

**Comment by HelenClifton** [comment]
Hi @mzuehlke I'm able to load and display this aerosol data source on its own.

I've also just tried loading a data source **esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1** followed by the **esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1** and then the Cloud dataset is displayed fine.

So the problem only seems to happen if the **aerosol** data is loaded first. I don't know why that should be.

**Comment by forman** [comment]
Cannot reproduce this in Cate Desktop 1.0.1.dev1. Can anyone else?

**Comment by HelenClifton** [comment]
I can't reproduce in Cate Desktop 1.0.1.dev1 either.
This can be closed.
