### ISSUE TITLE
cate.webapi problem with consecutive ODP downloads

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate#460]
### Problem description

When downloading many datasets from the ODP consecutively the datasets are getting downloaded without an error message. Later on while attempting to open them an error occurs.

### Steps to reproduce the problem
As I encountered the problem while using a script to download, the script does the following in a  loop:

1. cate ds copy dataset-A --name local.dataset-A
2. cate ws new
3. cate res set res_A open_dataset ds_name=local.dataset-A
4. cate ws close

Repeat the steps multiple times for a variety of datasets. Even when there should be no more process with 'ps aux | grep "cate"' there still is  a 'cate.webapi.main' process listed. It is working as intended when this process got killed.

### Error Message
ValueError: ('No data_source found for the given query term'

### Workaround
0. pkill -f 'cate.webapi.main'
1. cate ds copy dataset-A --name local.dataset-A
2. cate ws new
3. cate res set res_A open_dataset ds_name=local.dataset-A
4. cate ws close

### Question
It does work now, but a user needs to be aware, that there might occur an issue with the cate.wabapi and that killing this process helps. Do we need to inform about this somewhere?

### Specifications 
cate-1.0.0, linux

**Comment by forman** [comment]
@HerzogStephan this is not a bug. `cate ws close` is mot intended to shut down the `cate.webapi.main` immediately. It will wait for approx. 30 minutes of inactivity before it shuts down on its own. Use `cate ws exit` to exit interactive mode and shut down `cate.webapi.main` immediately. I'll 

- [ ] update the `cate ws -h`  help text accordingly.
- [ ] update the `cate ws close -h`  help text accordingly.
- [ ] update the `cate ws exit -h`  help text accordingly.

**Comment by HerzogStephan** [comment]
Perfect! If I could label I would have labeled it as 'discussion' or 'support_request', because I did not know about it. Thus, this can be closed from my point of view.

**Comment by mzuehlke** [comment]
Does using `cate ws exit` instead of `cate ws close` removes the _error_ ?

**Comment by HerzogStephan** [comment]
It does not occur anymore, thus I think it does solve it.

**Comment by forman** [comment]
No more complains, so I guess this can be closed.
