### ISSUE TITLE
'Region constraint'-option for AEROSOL dataset returns 'code 20' error

### ISSUE THREAD

**Issue by MartinMonkos** [CCI-Tools/cate#462]
### Expected behavior

Description for 'spatial coverage' of dataset 'esacci.AEROSOL.day.L3C.AER_PRODUCTS.AATSR.Envisat.ORAC.03-02.r1' shows the values 'min_lon=-180, min_lat=-90, max_lon=180, max_lat=90' (= full coverage).

One should be able to subset the dataset with the 'Region constraint'-option.

### Actual behavior

Using the 'Region constraint'-option returns error as shown in the screenshot below:

![error_screenshot](https://user-images.githubusercontent.com/31618877/31607474-b982f688-b26c-11e7-8aef-d644ac842a70.png)
 
### Steps to reproduce the problem with Cate Desktop

1. Go to panel 'Data Sources'
2. Select 'ESA CCI Open Data Portal'
3. Click 'Download and/or open remote dataset' for the dataset 'esacci.AEROSOL.day.L3C.AER_PRODUCTS.AATSR.Envisat.ORAC.03-02.r1'
4.  Select checkbox 'Region constraint'. Insert for 'Lon. from' = -180 and 'to' = 180. For 'Lat. from' = -5  and 'to' = 5.
5. Select checkbox 'Download and make local data source (allocates to space on disk)' and type in any local filename.
6. Click 'Download & Open Local'

### Specifications 

Linux, cate-1.0.0

**Comment by MartinMonkos** [comment]
Downloading the full dataset (without any adjustments for *-constraints) worked fine.
However, it is not possible to open the dataset with 'region constraint' adjustment from local and the same error is returned.
Opening it from local by adjusting 'Time constraint' and 'Variables constraint' works fine. It seems like it is not possible to get a regional subset.

**Comment by kbernat** [comment]
Fixed via https://github.com/CCI-Tools/cate/commit/c902806ff773265cecc8a69fa0c08b11d2550543
