### ISSUE TITLE
No longer able to select dataset for operations

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#463]
### Expected behavior

Many operations have the dataset or dataframe as adjustable parameters. User should be able to select one of these resources to use.

### Actual behavior

The dataset or dataframe as parameters are greyed out / disabled. Example below:

![capture](https://user-images.githubusercontent.com/29569434/31612483-c441123e-b277-11e7-9e52-f7d276fefddb.PNG)

Looked at a sample of operations and it was the case for all of them.

### Steps to reproduce the problem

1. From operations panel, click on an operation then  click on Add Step

### Specifications 

Cate 1.0.0
Windows 7 Professional

**Comment by forman** [comment]
And there were compatible resources to select from?

**Comment by HelenClifton** [comment]
I've looked at this and can confirm that this behaviour only happens when there are no resources in the workspace. When resources are loaded into the workspace, then they can indeed be selected in the "New Operation Step" window.
So, the functionality is correct (good !) and this should be changed to a user experience issue, to make cate "nicer to use", especially for new users.
If the user tries to add an operation step when no resources are available, they should be informed that they need to open resource(s) in the Workspace panel first. We suggest that a toast notification appears if the user clicks "Add Step" in the Operations panel, and there are no available workspace resources. However the notifications need to allow for the fact that some operations need two resources in the workspace (e.g. pearson_correlation) and some do not require any workspace resources (e.g. read_csv)

**Comment by HelenClifton** [comment]
I've looked at this and can confirm that this behaviour only happens when there are no resources in the workspace. When resources are loaded into the workspace, then they can indeed be selected in the "New Operation Step" window.
So, the functionality is correct (good !) and this should be changed to a user experience issue, to make cate "nicer to use", especially for new users.
If the user tries to add an operation step when no resources are available, they should be informed that they need to open resource(s) in the Workspace panel first. We suggest that a toast notification appears if the user clicks "Add Step" in the Operations panel, and there are no available workspace resources. However the notifications need to allow for the fact that some operations need two resources in the workspace (e.g. pearson_correlation) and some do not require any workspace resources (e.g. read_csv)

**Comment by forman** [comment]
@HelenClifton  quick fix: add a tooltip saying that you can select resources once user opened datasets

**Comment by HelenClifton** [comment]
@forman Confirmed it is fixed in cate-2.0.0-dev.1.
