### ISSUE TITLE
read_csv operation has a parameter which isn't used

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#464]
### Expected behavior

"New Operation Window" for operation **read_csv**: expect to select parameters.

### Actual behavior

There is a parameter **more_args** which isn't used.

![more_arg](https://user-images.githubusercontent.com/29569434/31613974-a634def6-b27c-11e7-85b8-ac1b2b25e8aa.PNG)

### Steps to reproduce the problem

1. Go to operations panel, select read_csv
2. Click "Add Step"

### Specifications 
cate 1.0.0
Windows 7 Professional

**Comment by forman** [comment]
1. Parameters with such types should not appear in UI. 
2. `more_args` should be a keyword argument list of type `dict` anyway

**Comment by forman** [comment]
The UI now shows a text field so users can enter keyword-value pairs.

**Comment by HelenClifton** [comment]
Confirmed fixed with cate-2.0.0-dev.1
