### ISSUE TITLE
Address problems of a user working with Cloud and Aerosol:

### ISSUE THREAD

**Issue by kbernat** [CCI-Tools/cate#478]
[https://groups.google.com/forum/#!topic/cci-tools/STbnY6I3LGU](https://groups.google.com/forum/#!topic/cci-tools/STbnY6I3LGU)

> I randomly tried some datasets and retrieve various error messages, one example would be (see picture):
> 
> 
> This results in the following error message:
> set_workspace_resource() call raised exception: "'Dataset' object has no attribute 'lat'"
> 
> Another example is the dataset esacci.CLOUD.mon.L3C.CLD_PRODUCTS.MODIS.Aqua.MODIS_AQUA.2-0.r1. 
> I cannot load data with the desktop, but it works fine when using the command line interface.

![cci_issue_1](https://user-images.githubusercontent.com/5653988/33673990-350a5d58-daa6-11e7-80a6-93debe46a402.png)

**Comment by thomas-eldridge** [comment]
Has this issue been resolved? I attempted to work with cloud datasets late last week in version 1.0 dev 3, and whilst I saw no error message while downloading my Cate Desktop software failed to open the AVHRR cloud datasets at all - have other users experienced this issue?

**Comment by kbernat** [comment]
Hi @thomas-eldridge ,
latest version is 1.0 which definitely contains that bug, but now it's fixed in master branch and if you prefer to download installer - new release is planned in upcoming days.

**Comment by thomas-eldridge** [comment]
Thanks! When new version is available I will re-try!
