### ISSUE TITLE
Errors reported when running use case #2 happy path CLI script

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#493]
### Expected behavior

Ran the following happy path script on Windows machine:
https://github.com/CCI-Tools/cate/blob/master/scripts/uc02.bat

Expected it to complete without error

### Actual behavior

Following errors are reported:

> cate ds: error: Invalid date/time value: "'2006-01-01"
> cate ds: error: Invalid date/time value: "'2006-01-01"
> 

These can be worked around by editing the script and replacing the single quotes with double quotes in the **cate ds copy** commands.

There is then a further error 

> FileNotFoundError: File b'../testdata/produkt_klima_Tageswerte_20050715_20151231_07341_vers002.txt' does not exist
> 
> cate res: error: set_workspace_resource() call raised exception: "File b'../testdata/produkt_klima_Tageswerte_20050715_20151231_07341_vers002.txt' does not exist"
> 

This can be worked around by downloading the file onto the local machine and placing in a folder named "testdata", but if this is needed, the user should be instructed about this. 

### Further info

Any changes in the **uc02.bat** script related to reading the testdata file will also need to be implemented in the **uc02.sh** script.
CLI scripts for uc06 and uc09 happy paths do run without error.

### Steps to reproduce the problem

1. Download script to machine (home folder)
2. Open CLI interface 
3. Type **uc02.bat** 

### Specifications 

cate 1.0.0
Windows 7 Professional

**Comment by HelenClifton** [comment]
@mzuehlke , @forman , @JanisGailis : for info

**Comment by kbernat** [comment]
@HelenClifton 
We have to move whole 'scripts' folder to [https://github.com/CCI-Tools/cate-e2e](https://github.com/CCI-Tools/cate-e2e). At the moment cate-e2e repo contains only  unix shell scripts.

**Comment by kbernat** [comment]
With separate repo it's easier to fetch whole content (with sub-folders) - using "clone of download" button on front page of repository.

**Comment by HelenClifton** [comment]
@kbernat 
It's not so obvious but at the moment the  'happy-path' test scenario scripts are **only** in 
https://github.com/CCI-Tools/cate/tree/master/scripts
The scripts in https://github.com/CCI-Tools/cate-e2e/ are "additional scenario" scripts. They belong to the same use cases but are different from the happy paths.
I agree with you it would be handy to have everything in one place. And clearly labelled.
Also with instructions on how to download the while repository as you've just commented.

**Comment by JanisGailis** [comment]
Related:
#95

**Comment by JanisGailis** [comment]
@forman Do you agree with @kbernat and @HelenClifton that the 'scripts' folder should be moved from 'cate' repo to 'cate-e2e' repo?

**Comment by forman** [comment]
Fine with that!

**Comment by JanisGailis** [comment]
The happy path scripts have been moved to ``cate-e2e`` repository now.

The preferred way to use them is to clone the whole repository together with the test data and following instructions regarding running them.

**Comment by VPriemer** [comment]
I've cloned the whole cate-e2e repository and followed the instructions regarding running it. 
I've tried to run uc02.sh in the CLI on my Linux machine. 

Although the testdata is in the correct folder and exists, the following error occured:
cate res: error: File b'../testdata/produkt_klima_Tageswerte_20050715_20151231_07341_vers002.txt' does not exist

If I replace the ".." in the line:
cate res set station read_csv file="../testdata/produkt_klima_Tageswerte_20050715_20151231_07341_vers002.txt" delimiter=";" index_col="time"

with my complete path to the testdata folder ("/cmsaf/cmsaf-ops8/vpriemer/cate-2.0.0-dev.9/cate-e2e-master/happy_path/testdata/produkt_klima_Tageswerte_20050715_20151231_07341_vers002.txt") it works!

**Comment by HelenClifton** [comment]
@JanisGailis , @forman Please could you re-open it due to problem reported by @VPriemer  above - thanks !

**Comment by JanisGailis** [comment]
I think I know what's going on.

**Comment by JanisGailis** [comment]
Should be fixed now in ``cate-e2e`` on ``master`` branch.

**Comment by VPriemer** [comment]
I can confirm that it works now.

Cate2.0.0.dev10, CLI.

**Comment by VPriemer** [comment]
Could you also please fix it for the Scenario 1 of UC2? 
(https://github.com/CCI-Tools/cate-e2e/tree/master/validation/scripts/UC2/UC02_S1_v001.sh)
Thanks.

**Comment by JanisGailis** [comment]
@VPriemer Can you link to the relevant issue or make a new one? So that I can put it in my TODO list. I'll be able to attend it starting from 17th of May, but I have to put it in the TODO, otherwise I'll forget!

**Comment by VPriemer** [comment]
#641
