### ISSUE TITLE
Confusing requirements for ENSO index calculation (UC6)

### ISSUE THREAD

**Issue by thomas-eldridge** [CCI-Tools/cate#496]
### Expected behavior

When using enso_nino34 operation, expect to be able to provide a dataset from which the climatology values of SST are deduced.

### Actual behavior

Operation requires a file as an argument - file is a netCDF Dataset of climatology values. In current happy path, this requires that a user:
1. temporally aggregates an ingested SST dataset into months,
2. calculates long term means for each cell for each month
3. saves this as an external netCDF
4. ingests this netCDF as the argument in enso_nino34

### Suggestion

The steps above are not hinted at in the description of the enso_nino34 operation. More clarity is required so that users without access to these issue pages can work out what to do.

A better fix would involve having an option to calculate the climatology at the same time as calculating ENSO index: the user could provide the SST dataset and time period in the same dialogue box as for the enso_nino34 operation.

### Specifications 

Cate 1.0 dev 3

**Comment by forman** [comment]
Does the same apply to Cate **1.0**? 
Note that version **1.0 dev 3** is outdated.

**Comment by JanisGailis** [comment]
@thomas-eldridge I agree that this is confusing. The main issue here is that the generation of a representative climatology can easily take a lot of time (days, even), while the index calculation itself is a pretty fast operation, hence we can not really risk users running ``long_term_average`` each time they do an index calculation.

But I agree that it should at least be documented in the description that the reference dataset can be created using the ``long_term_average`` operation.
