### ISSUE TITLE
anomaly_external in UC6

### ISSUE THREAD

**Issue by thomas-eldridge** [CCI-Tools/cate#497]
### Expected behavior

anomaly_external operation requires that a user provides a external netCDF from which to calculate anomalies. Expect to be able to create, save and open this dataset for use in anomaly external

### Actual behavior

Working with soil moisture, climatology by month successfully prepared (using temporal_aggregation and long_term_average) and saved externally. When using anomaly_external, attempting to open this ds to use as reference, ds successfully located but dialogue box prompts user to 'save' (i.e. overwrite) rather than 'open'.

### Steps to reproduce the problem

Create climatology ds by
1. Downloading/ opening soil moisture
2. Applying temporal_aggregation
3. Applying long_term_average
4. Saving in workspace

Apply anomaly_external, attempt to provide saved ds as file argument.

### Specifications 

Cate 1.0 dev 3

**Comment by forman** [comment]
Does the same apply to Cate **1.0**? 
Note that version **1.0 dev 3** is outdated.

**Comment by JanisGailis** [comment]
Thank you! I can confirm this bug, will be fixed in the next development version.
