### ISSUE TITLE
Cannot correlate table (1D vals) with map (2D)

### ISSUE THREAD

**Issue by thomas-eldridge** [CCI-Tools/cate#498]
### Expected behavior

Expect to be able to compare the value of a pre-calculated ENSO index with a soil moisture anomaly.

### Actual behavior

Result of ENSO index calculation is a table of values for each time step. Comparison of ENSO index and soil moisture anomaly reveals that number of values is identical (~3650 for 10 year period). Error message says that 'the length of the time dimension differs between the given datasets'. 

Possible that this is occurring because the ENSO index is in a table?

### Steps to reproduce the problem

1. Create ENSO index (as in happy path/ follow steps for issue #496)
2. Create soil moisture anomaly (as in happy path/ follow steps for issue #497 - use anomaly_internal instead of anomaly_external)
3. Attempt pearson_correlation

### Specifications 

Cate 1.0 dev 3

**Comment by forman** [comment]
Does the same apply to Cate **1.0**? 
Note that version **1.0 dev 3** is outdated.

**Comment by JanisGailis** [comment]
Can not reproduce on:
```shell
cate --version
cate 2.0.0.dev2
```
I managed to do a person correlation of enso index and monthly aggregated soil moisture, where SM is a lat/lon/time cube and index is 1D, when both datasets have been subset using ``subset_temporal`` to have the same ``time`` dimension length.

By the way, ~3650 time steps are way too long for monthly datasets spanning 10 years. It should be exactly 120. Did you aggregate SM?

Closing for now, please re-open if persists!
