### ISSUE TITLE
subset_spatial op very slow with non-trivial polygons

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#508]
### Problem

`subset_spatial` op is *very* slow (too slow) with `mask=True` and `region` being a non-trivial polygons and when many grid cells have to be compared. 

This is probably because we compare for each grid cell individually if it intersects the polygon. Would be more efficient if we create the mask by rendering the polygon as a masked numpy array (binary image).

### Steps

In Cate Desktop:

1.  Select operation `read_necdf` and add step with with file name e.g. `"20100401120000-ESACCI-L4_GHRSST-SSTdepth-OSTIA-GLOB_LT-v02.0-fv01.1.nc"` 
2.  From countries layer select Germany (yes, SST is an ocean product, but still there are many coastal cells this way)
3.  Select operation `subset_spatial` and add step with `ds_1`, the selected POLYGON and mask on. 

This actually computes forever.

### Specifications 

Cate 1.1 dev1

**Comment by JanisGailis** [comment]
Note to self - start with profiling the code
