### ISSUE TITLE
Cate Desktop - Internal error

### ISSUE THREAD

**Issue by R4FFAELE** [CCI-Tools/cate#509]
### Expected behavior
Cate Desktop should run on my PC

### Actual behavior
Cate Desktop does not work on my PC. It pop-ups  the following error: "Cate service process exited with code 1

### Steps to reproduce the problem
run Cate Desktop.exe

### Specifications 
windows 7 enterprise service pack 1
processor: Intel(R) Core(TM) i5-4310U CPU @ 2.00 GHz
ram 8GB
64-bit OS
cate-1.0.0-Windows-x86_64 core installed

**Comment by R4FFAELE** [comment]
@forman Yes, I  have followed the installation  instruction, cate was installed before the Desktop. Cheers

**Comment by stjsalo** [comment]
Hi guys,

I have the same problem on Windows 10 enterprise. I also get the same error message on virtual machine ubuntu gnome 16.04 (running in virtualbox on the same windows 10 computer).

**Comment by stjsalo** [comment]
@forman I did a quick search and could not find any .log files in the \.cate -folder. I will definitely try the new version as soon as you release it!

**Comment by R4FFAELE** [comment]
@forman   I will definitely try the new version as soon as you release it! Do you have any schedule for the release ?

**Comment by forman** [comment]
:)

**Comment by forman** [comment]
Guess, we have the reason now:

  [10:47:55.267] [info] Splash says: Waiting for Cate service response...
  [10:47:55.268] [info] No response from Cate service after 1000 ms
  [10:47:55.373] [error] cate-webapi: Traceback (most recent call last):
    File "/Users/forman/cate-1.1.0.dev5/bin/cate-webapi", line 7, in <module>
      from cate.webapi.main import main
    File "/Users/forman/cate-1.1.0.dev5/lib/python3.6/site-packages/cate/webapi/main.py", line 58, in <module>
      from cate.core.wsmanag import FSWorkspaceManager
    File "/Users/forman/cate-1.1.0.dev5/lib/python3.6/site-packages/cate/core/__init__.py", line 35, in <module>
      from .ds import DataStore, DataSource, open_dataset, find_data_sources, DATA_STORE_REGISTRY
    File "/Users/forman/cate-1.1.0.dev5/lib/python3.6/site-packages/cate/core/ds.py", line 90, in <module>
      from .types import PolygonLike, TimeRange, TimeRangeLike, VarNamesLike
    File "/Users/forman/cate-1.1.0.dev5/lib/python3.6/site-packages/cate/core/types.py", line 44, in <module>
      import geopandas
    File "/Users/forman/cate-1.1.0.dev5/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
      from geopandas.io.file import read_file
    File "/Users/forman/cate-1.1.0.dev5/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
      import fiona
    File "/Users/forman/cate-1.1.0.dev5/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
      from fiona.collection import Collection, BytesCollection, vsi_path
    File "/Users/forman/cate-1.1.0.dev5/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
      from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
  ImportError: dlopen(/Users/forman/cate-1.1.0.dev5/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
    Referenced from: /Users/forman/cate-1.1.0.dev5/lib/libgdal.20.dylib
    Reason: image not found

  [10:47:55.481] [info] cate-webapi: Cate service process exited with code 1.
  [10:47:57.059] [info] Quit.

On Mac, the conda environment seems not correctly initialised, so GDAL (used by GeoPandas) cannot find its shared libs.

**Comment by forman** [comment]
Similar issue: https://github.com/NCAR/pynio/issues/16. Will try adding `poppler` (?) dependency for Mac only.

**Comment by forman** [comment]
@R4FFAELE and @stjsalo here is a new 2.0 pre-release that should fix the problem you see in 1.0: https://github.com/CCI-Tools/cate-desktop/releases/tag/v2.0.0-dev.1

You don't need a install Cate (Python) Core on your own, this is done by Cate Desktop now.

**Comment by forman** [comment]
@R4FFAELE and @stjsalo if you are still out there, we now have: 

* https://github.com/CCI-Tools/cate-desktop/releases/tag/v2.0.0-dev.7

Looking forward hearing from you.

**Comment by R4FFAELE** [comment]
@Norman

installation was not successfully on my  PC (Windows 7). I attach the log 
message.
Cheers
Raffaele



------------------------------------------------------------------------------------------------------------
Raffaele Crapolicchio - Serco SpA - for European Space Agency (ESA)
Directorate of Earth Observation Programmes
Mission Management & Ground Segments Department
Sensor Performance, Products and Algorithm Section

ESA-ESRIN | Largo Galileo Galilei 1 | 00044 Frascati | Italy
Phone: +39 06 94 180 699 | Fax: +39 06 94 180 632

**Comment by forman** [comment]
@stjsalo I see you your user name on your machine is `x x`, therefore it seems you ran into #568. We haven't got a fix for this because it originates from the `conda install` process.

**Comment by R4FFAELE** [comment]
@forman  I might have the same problem reported by @stjsalo  my user account on the PC is installed under: C:\Users\Raffaele Crapolicchi\.conda

**Comment by forman** [comment]
@R4FFAELE thanks! I guess I must find a workaround for #568 now.

**Comment by forman** [comment]
@stjsalo That's good, but I still try to find a solution for the whitespace problem

**Comment by forman** [comment]
We are no longer supporting Cate Desktop. Please use the web app from now on: https://cate.climate.esa.int/.
