### ISSUE TITLE
Make Cate HTTP User-Agent distinguishable

### ISSUE THREAD

**Issue by kbernat** [CCI-Tools/cate#510]
### Expected behavior

Cate should send User-Agent information (HTTP header) containing at least information about product, its version and native platform.

Examples of UA produced by top internet browsers are available at:
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent)

### Actual behavior

Requests sent by Cate looks like:
```
python-requests/2.18.4
Python-urllib 3.6
```
### Steps to reproduce the problem

use Wireshark or any other network monitor/analyzer

### Specifications 

All supported operating systems (Windows/Linux/Mac os)

**Comment by forman** [comment]
Should be now fixed by Chris' #536
