### ISSUE TITLE
AppImage lacks needed dependency

### ISSUE THREAD

**Issue by probonopd** [CCI-Tools/cate#517]
### Expected behavior

An AppImage is supposed to have no dependencies other than what can reasonably be expected to come with all target systems in their default installation.

### Actual behavior

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/75203218111599073c72e09bd77a9d44eff7f1b9/database/Cate-Desktop/screenshot.png)

### Steps to reproduce the problem

1. Download the AppImage on a machine with no Cate-related software installed
2. Run it 

### Specifications 

The latest AppImage on Ubuntu 14.04

Reference:
https://github.com/AppImage/appimage.github.io/pull/340

**Comment by KurtPfeifle** [comment]
Just FYI,, @probonopd: This "Cate Core" thingie is a Tarball about 600 MByte worth of Bytes....

**Comment by probonopd** [comment]
That makes it a great candidate for AppImageUpdate binary delta updates actually - so it should definitely be included in the AppImage.

**Comment by KurtPfeifle** [comment]
> *"That makes it a great candidate for AppImageUpdate binary delta updates actually - so it should definitely be included in the AppImage."*

Maybe that also makes it a great candidate to create an example *Cate-Desktop-Complete.AppImage* for CCI-Tools which they could accept as a pull request?

**Comment by forman** [comment]
Sounds good, we are looking forward receiving a PR or any other support!

**Comment by forman** [comment]
We now install / update dependencies auto-magically.

**Comment by KurtPfeifle** [comment]
@forman:

> We now install / update dependencies auto-magically.

Can you already foresee when will it be that there's an AppImage available with that change?
