### ISSUE TITLE
Show a data source's terms and conditions

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#518]
### Expected behavior

Insert the terms and conditions (if any) of each ODP data source on their abstract tab in the **DATA SOURCES** panel.

### Actual behavior

We do not have that feature yet.
 
### Specifications 

Cate Desktop 1.0

**Comment by forman** [comment]
Added label `ds` because we must make the T&C part of the API / data model.

**Comment by SabineEmbacher** [comment]
Norman told me:
"A new tab 'Licences'  should be added instead of adding it to the 'Abstact' tab"

**Comment by forman** [comment]
Fixed in 2.0.0-dev.10

**Comment by forman** [comment]
![image](https://user-images.githubusercontent.com/206773/38996821-4cf009ae-43ec-11e8-857d-2badee64c2f1.png)
