### ISSUE TITLE
Temporal aggregation failing on SST CCI L4 data

### ISSUE THREAD

**Issue by kjpearson** [CCI-Tools/cate#538]
### Expected behaviour

Temporal aggregation should open a daily dataset and generate a monthly "average" of some sort.

### Actual behaviour

For the SST CCI L4 dataset this now fails as Cate doesn't recognise the dataset as daily. The full error message is below. This breaks UC6 as you need to form a climatology for the reference dataset in the ENSO calculation.

Examining the dataset array sizes under the variables tab, I have different behaviour between this version and version 1-dev3

v2.0-dev.1
Array shape 122,3600,7200

v1.0-dev3
Array shape 7061,3600,7200

version1.0-dev3 does perform temporal aggregation

### Specifications 

Cate v2.0-dev.1  on my new iMac

Cate Desktop, version 2.0.0-dev.1

set_workspace_resource() call raised exception: "Temporal aggregation operation expects a daily dataset"

An error (code 20) occurred in Cate Core:

Traceback (most recent call last):
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/util/web/jsonrpchandler.py", line 192, in send_service_method_result
    result = future.result()
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/util/web/jsonrpchandler.py", line 269, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/webapi/websocket.py", line 284, in set_workspace_resource
    monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/wsmanag.py", line 323, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/workspace.py", line 599, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/workflow.py", line 632, in invoke_steps
    step.invoke(context=context, monitor=monitor.child(work=1))
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/op.py", line 215, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/ops/aggregate.py", line 165, in temporal_aggregation
    raise ValueError('Temporal aggregation operation expects a daily dataset')
ValueError: Temporal aggregation operation expects a daily dataset

**Comment by kjpearson** [comment]
To put this in context, I'm trying to re-run UC6 to create some plots for the newsletter so I've installed the latest Cate on my new iMac. The v1 Cate is on an old PC that is crippling underpowered and regularly hangs if I try to do any intense toolbox processing.

**Comment by JanisGailis** [comment]
Thank you for the bug report!

Can you provide me with the make_local parameters you used to retrieve the dataset, so that I get exactly the same thing?

**Comment by kjpearson** [comment]
That's a little tricky as I've been working from our local copy of the CCI data and ingesting the whole thing. I did try to double check the ODP but it was timing out on me. I'll try to double check this behaviour again by downloading a smaller temporal subset.

**Comment by forman** [comment]
Hey, this means the 2.0.0 could be installed on your Mac without any issues?

**Comment by kjpearson** [comment]
Sorry, I've tried a couple of time now to download just 3 years of data from ODP. It seems to be running fine and then dies with a timeout error. I don't know if it is me or if you would have more success.

File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

**Comment by kjpearson** [comment]
Hi Norman

Yes, I downloaded and ran the cate-desktop-2.0.0-dev.1.dmg file and everything seemed to install just fine.

**Comment by forman** [comment]
Kevin, the timeout indicates that the ODP service went down while you were downloading. 
Really good to hear that Mac installation is fine now.

**Comment by JanisGailis** [comment]
Can not reproduce on:
```shell
cate --version
cate 2.0.0.dev2
```
The following works fine on CLI:
```shell
cate ds copy esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1 --name SST_2006_2007 --time "2006-01-01,2007-12-31" --region " -175,-10,-115,10" --vars "analysed_sst,analysis_error"
cate ws init
cate res open sst local.SST_2006_2007
cate res set sst_mon temporal_aggregation ds=@sst
cate res print sst_mon
```

The same steps can be used on the GUI, and I can then preview the aggregated dataset and step through it.

I'll close this now, but please re-open if this persists!

**Comment by kjpearson** [comment]
This seems to happen unpredictably. I have been able to start the temporal aggregation operation today (although it has never completed) but then I have started getting this error again even after a restart. I am now using data from the ODP downloaded to my local disk by Cate and so now a "local data source". It happens both for a small 2 year subset (2000-2001) and on the full 20 year dataset.

**Comment by JanisGailis** [comment]
It would be great if you can find a way how to reproduce it. The operation should be deterministic, so if you use the same data with the same input parameters it should either always fail or always work. Theoretically :)

By the way, what's the output of ``cate --version`` in the CLI?

**Comment by kjpearson** [comment]
It reports cate 2.0.0.dev1 in the CLI too.

I've left the temporal_aggregation operation running on the 20 year dataset but after 4 days it still hasn't completed. 

If this works on other macs, I'm wondering if there is something peculiar about my configuration that is causing me these problems.

**Comment by HelenClifton** [comment]
@JanisGailis , @kjpearson I've just seen it when running use case #6 happy path on cate  GUI on a Windows machine (cate 2.0.0-dev.1)
![capture](https://user-images.githubusercontent.com/29569434/37339683-5f91cab2-26b3-11e8-950c-aa1135fe9fc6.PNG)
Traceback: 
[uc06.txt](https://github.com/CCI-Tools/cate/files/1806710/uc06.txt)

Some steps to reproduce it:

Highlight data source: esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.03-2.r1

Click on “Download and/or open remote dataset"

In “Download Data Source” window:
•	Time Constraint : start time of 2007-01-01 and end time of 2007-12-31
•	Region Constraint, Lon. from: 72, Lon. to: 85, Lat. from: 8, Lat. to: 17
•	Variables Constraint: sm and sm_uncertainty 
•	Select “Download and make local data source“ and enter Unique identifier SOIL_2007
•	Click on “Download & Open Local”
(Note: takes approx. 1 hour to download)

Rename the resource as sst

Select temporal_aggregation from the list of operations, click on Add Step
In the “New Operation Step” window:
•	Select resource sst
•	Leave Method as the default value
•	Click “Add Step”

**Comment by kjpearson** [comment]
Cate 2.0.0.dev3 update: The CLI now allow me to open the data set, so I get past the problem in #557. However, I still get the original error message when performing temporal_aggregation. The GUI and CLI show the same behaviour.

**Comment by JanisGailis** [comment]
I can reproduce this now in Cate 2.0.0.dev7.

It must be something in one of the underlying libraries, as the same Cate code works fine in an older environment. I'll investigate what exactly is going wrong.
