### ISSUE TITLE
Opening Cate on Mac

### ISSUE THREAD

**Issue by kjpearson** [CCI-Tools/cate#550]
### Expected behavior

Cate should start normally each time even after a restart

### Actual behavior

Cate always fails to start the first time after a reboot of my iMac. The splash screen arrives but then there is a "Cate Desktop  - internal Error Failed to start within 10500ms". The second attempt always works fine. I'm guessing the background service is taking longer to start than Cate is allowing for?

### Specifications 

Cate 2.0.0 dev1 iMac

**Comment by forman** [comment]
That's right, the timeout is 10 secs. I'll make it configureable.

**Comment by HelenClifton** [comment]
@forman  I tested it on MacBook Pro running OS X 10.9.5 and it did not happen. 
But when testing using a Windows machine, running Windows 7 Professional, I see the error each time I reboot the laptop.

**Comment by forman** [comment]
@HelenClifton *reboot* means you really switch off and on, restart, right?

**Comment by HelenClifton** [comment]
@forman Yes it's after completely powering off the laptop then restarting again

**Comment by forman** [comment]
Like #551, I cannot reproduce this. My Mac opens Cate Desktop in one or two seconds after fully powering off the computer. 

![screen shot 2018-03-15 at 11 23 02](https://user-images.githubusercontent.com/206773/37457811-54489fc8-2843-11e8-848c-feb27960c722.png)

**Comment by forman** [comment]
I will set the timeout to 30 seconds. I will also put a setting `"webAPITimeout"` in `~/.cate/preferences.json`.

**Comment by HelenClifton** [comment]
@forman  it's now fine on my Windows laptop (cate-2.0.0-dev.7)
