### ISSUE TITLE
subset_point() output should be compatible with subset_spatial()

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#555]
### Expected behavior

I'd expect the `subset_point()` operation to output a `xarray.Dataset` instance exactly like `subset_spatial()` does. All metadata and all coordinate variables shall be preserved so that we can also visualize the single spatial cells without making any difference in the code.

### Actual behavior

`subset_point()` returns a `dict`. This is currently only useful in the API (i.e. Jupyter Notebook). It is useless in the CLI and Cate Deskop GUI, so we can neither plot it nor show it on the globe.

If the `dict` is really required by some use case, I suggest introducing an optional input `output_dict=False`.

### Specifications 

Cate 1 and 2-dev1

**Comment by JanisGailis** [comment]
It's used in UC9, but I think that's legacy, as the pearson_correlation() should work just fine with a dataset containing a single pixel.

**Comment by JanisGailis** [comment]
And it's ``tseries_point`` of course. There's no ``subset_point``. @forman, do you think we should rename it, and leave ``tseries_point`` as a deprecated alias?

**Comment by forman** [comment]
Sorry Janis, my fault. Marco added this recently to display dataset values in the GUI. We'll fix this here.

**Comment by forman** [comment]
@JanisGailis what about:

* `subset_spatial` should be able to deal with points
* `tseries_point` is a deprecated alias
* we rename `subset_point` to something else or make it a private operation

**Comment by JanisGailis** [comment]
The interface is different though. ``tseries_point`` takes an actual ``PointLike``, while ``subset_spatial`` takes a ``PolygonLike``. I'll see if ``subset_spatial`` can be converted to taking ``GeometryLike`` instead and what that entails. I'll also check how the outputs of the two operations differ. E.g., if ``tseries_point`` drops ``lat`` and ``lon`` coordinates or not, as ``subset_spatial`` should not do this.

In any case, ``subset_spatial`` should work with any valid Polygon, so it entails also working with a Polygon that would select a single point.
