### ISSUE TITLE
plot_map data plot type

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate#559]
Check the picture:
![cate_plots](https://user-images.githubusercontent.com/9655353/37408336-26dda7a6-279c-11e8-8c15-f2b3f87a6606.png)

Both plots are on the same grid. The first plot is current implementation, the second plot could be updated implementation. Should we change to the second type of plots, e.g., plot a colormesh on top of a map instead of a contour?

**Comment by JanisGailis** [comment]
Or present the choice to users as a parameter?

**Comment by forman** [comment]
@kjpearson, @VPriemer, what do you think?

I'd vote for a parameter.

What worries me more is that the two images are spatially misaligned. The 1st image is a zoomed-in version of the 2nd.

**Comment by VPriemer** [comment]
I'd vote for a parameter as well.

**Comment by kjpearson** [comment]
Yes, make it a parameter (with one of them as a default). It's always good to give the user flexibility.

**Comment by JanisGailis** [comment]
@forman, I don't think the first image is zoomed out. I think it's just that the filled contour plot doesn't interpolate values beyond actual data points at pixel centers.

OK, the consensus seems to be clear. I'll make a ``contour_plot=False`` parameter, as the pixel mesh seems a more correct representation of data in a general case. Thanks everyone!
