### ISSUE TITLE
Select all pixels crossed by a given polygon

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate#560]
### Expected behavior

As mentioned by @forman in #507, the operation should select all pixels crossed by the polygon.

### Actual behavior

Currently ``subset_spatial()`` only selects pixels whose centers fall inside the polygon:
![subset_spatial_now](https://user-images.githubusercontent.com/9655353/37412275-e044c050-27a4-11e8-9ac3-cc9b6db4e500.png)
![subset_spatial_now1](https://user-images.githubusercontent.com/9655353/37412404-2166cdc6-27a5-11e8-9237-764c073cc1c3.png)

**Comment by JanisGailis** [comment]
In the new implementation:
![pad_pixels](https://user-images.githubusercontent.com/9655353/37422742-36d48ad8-27bc-11e8-91c0-0a00e3b64d1a.png)

**Comment by forman** [comment]
Perfect!
