### ISSUE TITLE
CLI (and WebAPI) take too long to launch

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#58]
Both the CLI (and the WebAPI service) import _all_ package dependencies the CCI Toolbox has. This is because all operations in `ect.ops` are also imported which import packages such as `cartopy`, `basemap`, `matplotlib`, `pandas`, `xarray` which again import their own dependencies.

Both the CLI (and possibly the WebAPI service) must be modularized so that individual commands/actions have their own modules which will import only the desired packages. This is more important for the CLI, because the WebAPI is usually launched only once and remains in memory as a demon process. However, unit-level tests that require starting/stopping the service currently execute very slow due to the reasons stated above.

**Comment by mzuehlke** [comment]
It seems at least in some part to be a problem of python itself. The startup time has more than doubled between python 2 and python 3. 

An interesting article (no solution included 😞 ):
[Reducing Python's startup time](https://lwn.net/Articles/730915/)

**Comment by forman** [comment]
Let's refactor out the web-service instantiation from CLI unit-tests and use a mock instead.

**Comment by forman** [comment]
Started this because of #465

**Comment by forman** [comment]
Closing this, as there is currently no much more we can (easily) do.
