### ISSUE TITLE
Too many "Loading Pixel Values" 

### ISSUE THREAD

**Issue by esacci** [CCI-Tools/cate#581]
dev7 (Mac).

How to recreate - (1) Select esacci.Fire.day.L4.BA.multi-sensor.multi-platform.MERIS.v4-1.r1, (2) constrain download to "burned_area" variable, (3) continue with "Download and open local copy", (4) the download seems to have completed, I'm not entirely sure, may have completed downloading or not, (4) when trying to render the fire dataset many "Loading pixel values" dialog widgets open (See screenshot below) ; if this is a purely GUI issue, then would be nice for only one such dialog widget to appear, (5) the rendering of the fire dataset seems to hang, or perhaps it's something to do with the complexity or size of the fire dataset ; it's been in the same hanging state (see attached image) for about 10 minutes.

Speculation - perhaps this hanging occurs because of the prior state of Cate before I downloaded the Fire dataset ; as can be seen in screenshot, I'm using the new "layer split" feature.

<img width="1301" alt="screen shot 2018-03-23 at 13 34 43" src="https://user-images.githubusercontent.com/29626821/37832331-2cde5258-2ea0-11e8-9ea1-5f5e8be7408d.png">

**Comment by forman** [comment]
Too bad, I'll completely remove the toasts.

**Comment by esacci** [comment]
The toasts are great. Just my personal humble opinion that the many 'Loading pixel values' ones pushed the earlier ones out of the way.

**Comment by forman** [comment]
I mean, I will just remove the "loading pixel value" toasts. They occur every time we invoke a "remote" operation in the Python backend. Even loading a single pixel value is done that ways, but we can also make a REST call in this case which will avoid toasts being shown.

Actually, I don't like the way we have implemented showing pixel values, i.e. by clicking the globe. It may be more user friendly if values are loaded in the background when the mouse pointer resides on the same location, e.g. for a 0.5 seconds and then we would display a text bubble / tooltip text with the current position and all the variables' values at that position. 

What do you think?

**Comment by esacci** [comment]
I agree with your intuition Norman.

**Comment by forman** [comment]
I created #592 for this.
