### ISSUE TITLE
Representative default variables

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#590]
### Expected behavior

When a dataset is opened in the Cate Desktop, the geo-spatial variable displayed in the World View should be a *representative default variable*.

### Actual behavior

Cate Desktop displays the first geo-spatial variable it finds in a dataset. This is often not what a user expects, for example the if the first variable contains quality flags or is a statistical by-product rather then being a geo-spatial and geo-physical variable that represents the ECV of a given dataset.

### Specifications 

Cate Desktop 1.0 - 2.0.0-dev.8

**Comment by papesci** [comment]
The task to find the most significant variable for each data set  i think can be done only by a human. We can generate maps of all the variables to help the selection process but the final decision should be done by a human.

We can apply some statistics method like P-value or even a more sophisticated Random forest to identify the principal component but what is important for a machine might be no so important for humans and we risk to show a plot of 'number of observation' variable that i think is not so interested.

**Comment by forman** [comment]
Oh, I should have said that default variables should be provided by configuration, that is, by humans.
