### ISSUE TITLE
Drag and drop files on Cate's main window

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#597]
My cate software interface changed when I dragged CCI data from 'http://cci.esa.int/data#ftp' to the area under 'Local Data Source' above the 'details' button. 

This dragging was made in attempt to escape the seemingly 'forever' waiting time to download  data via the ESA CCI Open Data Portal.

**Comment by forman** [comment]
Surprisingly the Cate Desktop's main window accepts drag&drop from external link and displays the according web-page (this is because Cate Desktop is actually a Chromium-based browser window).

We may disable drag&drop until we really support it.

**Comment by forman** [comment]
Not only we can easily disable drag&drop we can also handle dropped files and invoke `read_xxx(file=file)` where `xxx`is based on the file extension.

**Comment by forman** [comment]
We can now drop the following file types: nc, txt, csv, json, geojson, shp, gml.
