### ISSUE TITLE
Unable to desplay fire data

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#599]
Cate Desktop, version 2.0.0-dev.8

get_data_sources() call returned a value that could not be converted to JSON

An error (code 30) occurred in Cate Core:

null

**Comment by forman** [comment]
Please tell use which dataset exactly you are referring to.

**Comment by Evadzi** [comment]
@forman 
Everything works fine now. I cant tell why it works now and not before..

**Comment by forman** [comment]
Closing this as we cannot reproduce it again.
