### ISSUE TITLE
data synchronization problem

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#602]
Although data ingestion from the open portal may be influenced by internet speed and other factors, data accessed using the open portal are queued, in the case of 2 data, the later is paused until the former completes download. Even if you have a local data that you want to import and delimit region for analysis, it is also added to the queue with no option to cancel a number of files queued and the tool kit user must wait until the files begin download.  

I will be glad if this issue can be resolved

**Comment by papesci** [comment]
Hi @forman ds module has export only synchronous methods. The asynchronous behavior is generally located in the webapi module. We can of course add some coroutine in ds operation to facilitate their asynchronous call.

**Comment by Evadzi** [comment]
@forman satisfied!!
