### ISSUE TITLE
New / save / close workspace toasts sometimes not displayed

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#619]
### Expected behavior

When creating a new workspace, saving a workspace or closing, expect green toasts to say that the operation has been successful (as seen with previous versions of cate)

### Actual behavior

File->New Workspace : no toast seen
File->Close Workspace : no toast seen

File->Save Workspace : Sometimes a toast will be seen. It depends how long it takes to save the workspace. If it is just a fraction of a second, there is no notification. If it takes about 1 second or more, there is a toast.

For other operations such as renaming a resource, or opening a dataset, toasts are seen.

In cases where no toasts are seen, it is confusing for user because it is not clear that anything has happened.

### Steps to reproduce the problem

See above

### Specifications 

cate-2.0.0-dev.9
Windows 7 Professional

**Comment by forman** [comment]
That's right, we only see toasts if an operation takes longer than 500 ms. 

How to fix: introduce parameter `show_toast_delay` and set it to zero for some operations, e.g. workspace save, load.

**Comment by HelenClifton** [comment]
Hi @forman  I'm seeing the toasts now in dev10.
On closing the workspace, you see a "Close Workspace" toast then a "New workspace" toast straight after.
Is this what you expect ?

**Comment by forman** [comment]
Yes. But I agree, it is a little confusing.
