### ISSUE TITLE
Aerosol data source cannot be downloaded using GUI with a limited time constraint

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#628]
### Expected behaviour

Expect to run through the use case #11 happy path using the GUI

### Actual behavior

The aerosol data source (*) used in the happy path is not shown in the list of ODP data sources in the GUI, because it is not on the whitelist.

(*)esacci.AEROSOL.mon.L3.AAI.multi-sensor.multi-platform.ms_uvai.1-5-7.r1

I did try adding it to the conf.py file to make it appear in the list on the GUI. Then I tried downloading it to local, but I got a ‘time’ error

![time](https://user-images.githubusercontent.com/29569434/39295080-04a5fc3a-492d-11e8-8170-8cdc6c4bc0e2.png)

So I then tried creating a local data source using the CLI, and this worked fine. Then I opened the local data source using the GUI and the happy path worked fine from then on.

### Steps to reproduce the problem

See above

### Specifications 

cate-2.0.0-dev.9
Windows 7 Professional

**Comment by HelenClifton** [comment]
In summary, the use case 11 happy path cannot currently be run end-to-end using the GUI. There are two options:
- Fix the problem which stops that aerosol data source being downloaded using the GUI, and then add the data source to the whitelist
- Use another data source for use case 11 happy path 

@JanisGailis, @forman : please comment and discuss

**Comment by forman** [comment]
Hi @HelenClifton has it the same error traceback as in #514?

**Comment by VPriemer** [comment]
For your note. On my Linux machine the happy path of UC#11 works well in the CLI.

**Comment by HelenClifton** [comment]
Thanks @JanisGailis and @forman . I've looked at this some more.
With the use case 11 happy path, I am applying the following constraints:

- Time Constraint: 2007-01-01 to 2007-01-31
- Region Constraint:
 o	Lon. from -180 to 180
o	Lat. from 60 to 90
- No variable constraints

If there is a time constraint but NO region constraint, dataset will load without problems
If there is NO time constraint but there is a region constraint, dataset will load without problems

If there is **both** a time constraint and a region constraint applied, then the error will occur

**Comment by JanisGailis** [comment]
@forman So this seems to be an issue of not being able to download a single time step.

In either way, that dataset should be added to the whitelist, as it works fine.

**Comment by forman** [comment]
Done.

**Comment by HelenClifton** [comment]
@forman Confirmed it is fixed in dev10
