### ISSUE TITLE
Problems with auto-update from cate-2.0.0-dev.9 to cate-2.0.0-dev.10 on Windows

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#633]
### Expected behavior

@forman Opened cate-2.0.0-dev.9 GUI.
Received a notification that a new cate version was available and that cate would be auto-updated.
Closed GUI
Expected cate to successfully auto-update.

### Actual behavior

The auto-update started and appeared to finish successfully.
But after the auto-update, the cate GUI was automatically opened and then the following error message appeared:

![internal eror - auto update](https://user-images.githubusercontent.com/29569434/39525744-683fc602-4e0c-11e8-9f40-0601bd50e3a6.PNG)

The I closed the GUI and opened it again, and this time the error was not shown.
The GUI said that it is cate-2.0.0-dev.10

![cate-auto-update](https://user-images.githubusercontent.com/29569434/39526027-25747b46-4e0d-11e8-8ff3-e5d6987873df.PNG)

However folders for both 2.0.0.dev10 and 2.0.0.dev9 were present in the home .cate folder.
Then running a use case, one of the operations failed and I generated a traceback and it contained paths to dev9 files:
[time_error.txt](https://github.com/CCI-Tools/cate/files/1967431/time_error.txt)
So I'm not sure what my installation actually is

(Typing cate --version on the CLI gives cate 2.0.0.dev10)
### Steps to reproduce the problem

See above

### Specifications 

Windows 7 Professional

**Comment by forman** [comment]
@HelenClifton if the Cate Desktop about box shows **CLI env: <unknown>**, this means the GUI uses an already-running Cate WebAPI service *or* you are running the Cate WebAPI from sources. Before you run Cate Desktop, can you please check sure there is no service already running (use Task Monitor).

**Comment by HelenClifton** [comment]
@forman Thanks, I will retest it when dev11 is released

**Comment by forman** [comment]
@HelenClifton we will make the `~/.cate/cate-desktop.log` more detailed

**Comment by HelenClifton** [comment]
Hi @forman  trying to update from dev.10 to dev.11, I've made several attempts but unfortunately can't get the auto-update to work.
When the GUI is open, I get the notification about the new version.
When I exit cate, the Cate WebAPI service is still running  so I stop it with Task Manager.
Then I re-open cate and it is still dev.10:
![capture](https://user-images.githubusercontent.com/29569434/40661450-5df9e71c-6343-11e8-80b7-9a5016b85c5b.PNG)
Here is the log file which you mention above:
[cate-desktop.log](https://github.com/CCI-Tools/cate/files/2048334/cate-desktop.log)

**Comment by HelenClifton** [comment]
@forman Auto-update was successful on my Windows machine, going from dev.11 to dev.12, then dev.12 to dev. 13.
Closing this issue.
