### ISSUE TITLE
Problems with auto-update from cate-2.0.0-dev.9 to cate-2.0.0-dev.10 on Mac

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#635]
### Expected behavior

@forman Opened cate-2.0.0-dev.9 GUI.
Received a notification that a new cate version was available and that cate would be auto-updated.
Closed GUI
Expected cate to successfully auto-update.

### Actual behaviour

The auto-update started and appeared to finish successfully
The GUI said that it is cate-2.0.0-dev.10. It is displaying the new dev10 operations such as the Hovmoeller plot.
However I noticed that esacci.AEROSOL.mon.L3.AAI.multi-sensor.multi-platform.ms_uvai.1-5-7.r1 was not appearing in the whitelist. Looking at file **~/.cate/conf.py**, it had not been updated from the previous iteration.
The file **~/.cate/cate-location** had been updated, but is pointing to ~/cate-2.0.0.dev9
The home folder contains a folder for cate-2.0.0.dev9 but not cate-2.0.0.dev10

### Steps to reproduce the problem

See above

### Specifications 
Using MacBook Pro OS X version 10.9.5

**Comment by forman** [comment]
@HelenClifton as you said, the issue seems to be the `~/.cate/conf.py` that for some reason isn't updated. That should apply to all installations, not only on Macs.

**Comment by HelenClifton** [comment]
Hi @forman, I saw the esacci.AEROSOL.mon.L3.AAI.multi-sensor.multi-platform.ms_uvai.1-5-7.r1 listed on the GUI of the Windows machine but not on the Mac. But the reason for this was, on the Windows machine,  I had previously edited the file ~/.cate/conf.py manually,  to add the esacci.AEROSOL.mon.L3.AAI.multi-sensor.multi-platform.ms_uvai.1-5-7.r1 to the whitelist.
Hope this helps to clarify it.

**Comment by forman** [comment]
Hi @HelenClifton, yes, it does. Also note that if `~/.cate/conf.py` does not exists, it will be created by. If it already exists, nothing happens so a user's changes are preserved.

However, I will change the code so that even if `~/.cate/conf.py` exists, we will always write a `~/.cate/conf-template.py` that is up-to-date.

**Comment by forman** [comment]
Doesn't seem to appear anymore. Closing.
