### ISSUE TITLE
Make default variables configurable per dataset

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#638]
### Expected behavior

@forman, @VPriemer An initial set of default variables has been established. Several of the proposed default variables are different between datasets of the same ECV.

### Actual behavior

The current configuration file allows configuration of default variables per ECV (implemented in #590)
Should be updated as above.

**Comment by forman** [comment]
@HelenClifton did you mix up expected with actual behavior?

>  Several of the proposed default variables are different between datasets of the same ECV.

However, a single default variable does usually not occur in more than one ECV product.

Therefore I don't see any actual problem with the current approach which is btw also applicable to derived datasets that have IDs that are different from the original ESA ODP dataset IDs.

**Comment by HelenClifton** [comment]
@forman Closing as obsolete
