### ISSUE TITLE
No Mac v2s Work Anymore; Cate 2.0.0.dev10 to dev1.

### ISSUE THREAD

**Issue by esacci** [CCI-Tools/cate#639]
No Mac v2s Work Anymore. 

I've reverted all the way down to the first v2 dev and it's the same as the other installations. Either the installation itself doesn't work or it doesn't work at startup.

Failed installations and failed startups seem to be because can't attach to local (python) server.

I'd be fine uninstalling Python as well as the toolbox installations to start afresh, but removing all Python seems to be not straightforward.

[cate-desktop (2.0.0.dev9-startingFirstTime).log](https://github.com/CCI-Tools/cate/files/1983091/cate-desktop.2.0.0.dev9-startingFirstTime.log)
[cate-desktop(2.0.0.dev8-failedInstall).log](https://github.com/CCI-Tools/cate/files/1983092/cate-desktop.2.0.0.dev8-failedInstall.log)
[cate-desktop(2.0.0.dev10-duringInstallation).log](https://github.com/CCI-Tools/cate/files/1983093/cate-desktop.2.0.0.dev10-duringInstallation.log)

**Comment by esacci** [comment]
This is the log from the failed installation of dev.1.dmg -

[cate-desktop.log](https://github.com/CCI-Tools/cate/files/1983216/cate-desktop.log)

**Comment by esacci** [comment]
Recreating the steps for problematic installation of dev.10.dmg -

1. Rebooted machine
2. Removed .cate from /Users/<nameOfHomeDirectory>
3. Removed Cate Desktop from Applications directory
4. Execute cate-desktop-2.0.0-dev.10.dmg
5. Dialog-box asks for Cate Desktop to be copied to Applications directory. Done.
6. Click on Cate Desktop in Applications directory
7. Dialog-box asks "...Are you sure you want to open it?". Click Open. 
8. Cate Desktop Setup asks to select installation option. Automatic setup chosen. Click Next.
9. Run Setup Tasks dialog appears.
10. Run Setup Tasks dialog shows setup failure.
<img width="595" alt="screen shot 2018-05-08 at 10 42 56" src="https://user-images.githubusercontent.com/29626821/39750275-c0328e2c-52ac-11e8-913e-2ddf27dc5c00.png">
11. Log-file located in .cate directory
[cate-desktop.log.txt](https://github.com/CCI-Tools/cate/files/1983303/cate-desktop.log.txt)
<img width="942" alt="screen shot 2018-05-08 at 10 47 29" src="https://user-images.githubusercontent.com/29626821/39750471-3db10798-52ad-11e8-89e0-017eba319a14.png">
12. As a test, I try http://127.0.0.1:9090/ on chrome browser
<img width="343" alt="screen shot 2018-05-08 at 10 48 31" src="https://user-images.githubusercontent.com/29626821/39750541-65d7c522-52ad-11e8-8f35-70fc3e986a28.png">

Note - the file '/Users/edpechorro/.cate/webapi-info.json' (see above) does not exist.

13. Press Cancel on Run Setup Tasks.

**Comment by esacci** [comment]
Workaround : Build Cate & Cate Desktop from Source, then run.

1. Do steps described in https://github.com/CCI-Tools/cate section "Installation from Sources"
2. Install Anaconda (https://www.anaconda.com/download/#macos) for Python 3.x
3. Do steps described in https://github.com/CCI-Tools/cate section "Using Conda"
4. Do 1 step only described in https://github.com/CCI-Tools/cate section "Using Standard Python" which is "python3 setup.py install --user".
5. Do 1 step only described in https://github.com/CCI-Tools/cate section "Getting started" which is to test the installation as follows - "cate -h".
6. Do all steps apart from last step ("npm start") described in https://github.com/CCI-Tools/cate-desktop section "Setting up Cate Desktop". Note, after the git clone then need to install Node.js - https://nodejs.org/en/, 8.11.1 LTS rather than 10.0.0 Current. 
7. cate-webapi-start --port 9090 & 
8. npm start. To close server : cate-webapi-stop --port 9090

**Comment by esacci** [comment]
I again cleared all previous installs (installer versions and other versions built from code) and this time tried installing dev2-10 through installer and pointing to existing version of Anaconda on my machine. Installation failed.

Log attached.

<img width="599" alt="screen shot 2018-05-11 at 08 49 35" src="https://user-images.githubusercontent.com/29626821/39913055-83064b1c-54f8-11e8-9e55-fcfbea67843b.png">
[cate-desktop.log](https://github.com/CCI-Tools/cate/files/1994425/cate-desktop.log)

**Comment by forman** [comment]
@esacci Ed, I have absolutely no clue what's going on on your machine. In dev11 which I will release later, we output more information to `~/.cate/cate-desktop.log` in the hope this will help us.

**Comment by forman** [comment]
Has been clarified, the problem was that the wrong Miniconda environment was used due to a misconfigured `PATH` environment variable.
