### ISSUE TITLE
testdata location error for UC#2 S1

### ISSUE THREAD

**Issue by VPriemer** [CCI-Tools/cate#641]
### Expected behavior

UC02_S1_v001.sh should run without an error. 

### Actual behavior

The following error occurs (although the testdata is in the correct folder and exists).
cate res: error: File b'../../testdata/produkt_klima_tag_19620501_20161231_01981.txt' does not exist

If I replace the "../.." in the line:
cate res set station read_csv file="../../testdata/produkt_klima_tag_19620501_20161231_01981.txt" delimiter=";" index_col="time"

with my complete path to the testdata folder ("/cmsaf/cmsaf-ops8/vpriemer/cate-2.0.0.dev10/cate-e2e-master/validation/testdata/produkt_klima_tag_19620501_20161231_01981.txt") it works!

There was a similar problem for the happy path of UC#2. (see #493)

### Steps to reproduce the problem

1. clone the whole cate-e2e repository 
2. bash UC02_S1_v001.sh (script is here: https://github.com/CCI-Tools/cate-e2e/tree/master/validation/scripts/UC2/UC02_S1_v001.sh)

### Specifications 

Cate-2.0.0.dev10, Linux, CLI

**Comment by JanisGailis** [comment]
@VPriemer Should work now

**Comment by VPriemer** [comment]
@JanisGailis Yes, it works now. Thanks.
