### ISSUE TITLE
Setup error: directory has access restrictions

### ISSUE THREAD

**Issue by hans-permana** [CCI-Tools/cate#642]
### Expected behavior

Can proceed with Cate installation

### Actual behavior

Encountered an error message on the first page of the Cate installation dialog.
![cate-issue](https://user-images.githubusercontent.com/7643370/39811970-1eb17010-538b-11e8-8e91-1c2f262108be.png)

### Steps to reproduce the problem

1. Download Cate installer
2. Run the installer (no previous installations)

### Specifications 

Ubuntu 16.04, cate-2.0.0-dev.10

**Comment by hans-permana** [comment]
upgrade Electron to version 2 did not solve the issue. The workaround https://github.com/CCI-Tools/cate-desktop/commit/4467d6fd1237f6bf157ff3002a0364da23c308cc solved this issue for now.

**Comment by forman** [comment]
Closing this as we don't the error anymore.
