### ISSUE TITLE
Error downloading Cloud ECV dataset from ODP

### ISSUE THREAD

**Issue by aghenry** [CCI-Tools/cate#643]
### Expected behavior / Step to reproduce the pb

Downloading the dataset " Esacci.CLOUD.mon.L3c_products.multi-sensor.multiplatform.ATSR2-AATSR.2-0.R1" with
Region constraint : longitudes between -8 and 3, latitudes btw 35 and 44. 
Dates constraints : 01.01.2002 - 01.01.2012
Variables constraintes : 6 variables selected (Can not have the view of the exact variables in the error dialogue)

### Actual behavior

Operation error (AttributeError) : 'Timedelta' object has no attribute 'astype' 
Days= (delta.astype('timedelta64[D]') / day) + 1
### Specifications 

Cate desktop 2.0.0-dev.10 , last python version . All the system has been updated

Thanks, 

Agathe from Climate departement Office - ECSAT

**Comment by forman** [comment]
@JanisGailis the error occurs in `cate.core.opimpl._get_duration` where it is assumed that `delta` is always a `datetime64`: 

* https://github.com/CCI-Tools/cate/blob/9e00ab24b9b53135267520fa88842f16d3219085/cate/core/opimpl.py#L515-L528

**Comment by forman** [comment]
@aghenry Next time you see this (or any other) error message, please check **Copy error report to clipboard** and paste it here:

![image](https://user-images.githubusercontent.com/206773/39824384-805b7f62-53af-11e8-9321-1e2e9eef0fb5.png)

**Comment by forman** [comment]
@JanisGailis please review workaround in in 107dbfc. Note is is not a solution to this issue. The actual issue is that Cloud ECV from OPeNDAP is not correctly decoded as `np.datetime64`.

@papesci please investigate why time coordinate variable of Cloud ECV is not correctly decoded as `np.datetime64` when originating from OPeNDAP. Is this a general problem?

@aghenry Please reopen if this error persists.

**Comment by HelenClifton** [comment]
Hi  @papesci  as requested I tried this on my Windows machine with regional and temporal constraints as above. I didn't know which 6 variables had been selected so I selected all variables.
The dataset downloaded to local without problems (it took about an hour) and was successfully displayed on the GUI.
I was using cate-2.0.0-dev.10 from clean install.

**Comment by HelenClifton** [comment]
@papesci Applying same constraints as above, but opening remotely, I got the error below.
Here's the error log: [issue-643.txt](https://github.com/CCI-Tools/cate/files/2009147/issue-643.txt)

![issue-643](https://user-images.githubusercontent.com/29569434/40117669-17d9791e-5907-11e8-8169-135b473679d1.PNG)

**Comment by JanisGailis** [comment]
Checking for ``dtype`` seems a sane workaround. Otherwise, seems like an issue with using OpenDAP.

**Comment by papesci** [comment]
Downloading manually all the files from Esacci.CLOUD.mon.L3c_products.multi-sensor.multiplatform.ATSR2-AATSR.2-0.R1 data set and open them one by one doesn't look to have glitch inside or wrong data type. I am writing a script to check openDap query among this dataset askgin for random region, time and variable. Maybe we can identify the glitch.
