### ISSUE TITLE
Cate upload to Anaconda Cloud fails

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#653]
### Expected behavior

As part of the release process, Cate conda packages should be uploaded to Anaconda Cloud.

### Actual behavior

Anaconda upload fails from Travis Mac and Linux build. AppVeyor Window 10 uploads succeed.

Issue reported in [anaconda-client](https://github.com/Anaconda-Platform/anaconda-client/issues/473)

### Specifications 

Mac and Linux
Cate 2.0.0.dev11

**Comment by hans-permana** [comment]
solved by removing the **_app_** section in the recipe
