### ISSUE TITLE
Unable to return to working environment after selecting website link

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#658]
Unable to return to cate desktop working window after clicking on link in abstract of ESA landcover data (see attached pix a)

PIX A
![actual_behavior_landcov3](https://user-images.githubusercontent.com/37798521/40224381-4873dbfc-5a86-11e8-8a21-b9ec1cec0810.GIF)

-The expected result is for the clicked-link to open in new window. I checked--this is only possible if I select the control key before clicking on the website link. This should be the default..(See attached pix b)

PIX B

![expected_landcov2](https://user-images.githubusercontent.com/37798521/40224696-33b239a6-5a87-11e8-90c0-5c7168d564f5.GIF)

Thanks

**Comment by forman** [comment]
Will quick fix this by opening new Cate Desktop windows for the clicked link. Currently not trivial to open a new desktop browser for any clicked link.
