### ISSUE TITLE
ESA sea-level data not correctly displayed

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#661]
*What I expected Cate to do.*

I tried to call ESA sea-level data from the open data source (esacci.sealevel.mon.ind.msltr.multi..... ) for analysis. Cate is expected to display data for ocean-spaces. 
The first was to display global data without regional constraints and secondly with regional constarints. 

*What Cate does instead or doesn't do at all.*
Sea-level data is inverted (north-south) without regional constraints (A1) and with regional constraints (A2)

A1

![esa_sea-level_data](https://user-images.githubusercontent.com/37798521/40774075-f658c9d8-64c4-11e8-80a0-616428fa8872.GIF)

A2

![esa_sea-level_data_reg_const](https://user-images.githubusercontent.com/37798521/40775800-3ca6f596-64c9-11e8-8ad8-4be7ce3a09a4.GIF)

Hint-the same global data displays well using other climate data viewer(see A3) and subset data displays well in cate (A4) after I first carried out spatial sub-setting of the sea-level data using other climate toolkits 

A3

![esa_local_mean_sea_level-ncview](https://user-images.githubusercontent.com/37798521/40775656-e237354e-64c8-11e8-8603-50b9f6c164f8.GIF)

A4

![subset_msl](https://user-images.githubusercontent.com/37798521/40775629-d09d113c-64c8-11e8-835b-12dd3b3b8212.GIF)

### Steps to reproduce the problem

1. Kindly attempt downloading esacci.sealevel.mon.ind.msltr.multi..... 
2. first try for the global data (no regional constraints)
3. Try with regional constraints e.g lon -80 40, lat -40 40

### Specifications 

Cate Desktop 2.0.0-dev 12

**Comment by JanisGailis** [comment]
@forman @papesci Could this be because some changes we've made to normalization?

@Evadzi Can you try opening the non-constrained dataset and then running ``normalize`` operation on it?

**Comment by Evadzi** [comment]
@JanisGailis  I checked! it is same with or without normalization.

**Comment by JanisGailis** [comment]
Thanks for checking! This is something that should be accounted for when opening datasets. I'm just slightly perplexed, because I was quite sure @kbernat had this already fixed at some point.

**Comment by forman** [comment]
This problem should be addressed by #644 and #645.
