### ISSUE TITLE
Cate Desktop Errors on invoking a 'Save File' dialog

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate#665]
### Expected behavior

Cate GUI should not error out when trying to save a dataset to a file.

### Actual behavior

In certain cases (see below) Cate Desktop errors out when trying to open the 'Save File' file browser:
![cate_save_file_error](https://user-images.githubusercontent.com/9655353/41092901-3deaa926-6a4a-11e8-83ef-576a94e63e4d.png)

### Steps to reproduce the problem

1. Open the operation dialog of an operation that has a 'save file' file path as an input. Such as ``write_netcdf4``, ``write_netcdf3``, etc.
2. Write something in the text field for ``file``.
3. 'Change your mind' and try to invoke the file browser instead by pressing the button with three dots.
4. Observe the error

### Specifications 

Cate Desktop v2.0.0-dev12
Windows 10

**Comment by JanisGailis** [comment]
Thanks, yes, I figured out how to proceed :) Just wanted to log the issue such that it it's not forgotten and gets fixed by someone at some point.

**Comment by forman** [comment]
Oh, same as #764.
