### ISSUE TITLE
ODP data sources not loading after auto-update to dev. 13 on mac

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#676]
### Expected behavior

@forman On mac, auto-update was performed from dev.11 to dev.12, then from dev.12 to dev.13.
Opened the dev.13 GUI
Expected to see a task started which loads the ODP data sources

### Actual behavior

The task to load the data sources did not start. 
So data sources did not load and the list of data sources remained empty.

### Steps to reproduce the problem

See above 

### Specifications 

MacBook Pro OS X version 10.9.5

**Comment by hans-permana** [comment]
hi @HelenClifton, how do the values of `included_ds_ids` and `excluded_ds_ids` variables look like in `~/.cate/conf.py`?

**Comment by forman** [comment]
@HelenClifton do you see anything in the developer console or the logs?

@hans-permana mentioned values of `included_ds_ids` and `excluded_ds_ids` variables of `~/.cate/conf.py`, but they shouldn't matter, as your problem is that the *loading task* doesn't start at all.

**Comment by HelenClifton** [comment]
Hi @forman , @hans-permana  This is very strange, but I opened the GUI this morning using exactly the same machine, and this time the "loading ODP data sources" task started and the ODP data sources were correctly loaded (as were the local ones)
I will close this issue, as I cannot reproduce it.
I will monitor what happens with the auto-install of the next release.
