### ISSUE TITLE
Error when downloading aerosol dataset as part of use case 11 happy path

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#677]
### Expected behavior

Running use case 11 happy path with cate GUI.
Downloaded aerosol data
Expected successful download (it's known this worked with cate-2.0.0-dev.10)

### Actual behavior

An error occurred during download
![capture](https://user-images.githubusercontent.com/29569434/41236372-7b5b11b8-6d80-11e8-9e71-03f7f13fed8c.PNG)

Here's the traceback:
[aerosol_download_trace.txt](https://github.com/CCI-Tools/cate/files/2090281/aerosol_download_trace.txt)

### Steps to reproduce the problem

1. Highlight data source: esacci.AEROSOL.mon.L3.AAI.multi-sensor.multi-platform.ms_uvai.1-5-7.r1

2. Click on “Download and/or open remote dataset”. 

3. In “Download Data Source” window:
•	Select Time Constraint and enter start time of 2007-01-01 and end time of 2007-03-31

•	Select Region Constraint, enter:
o	Lon. from:  -180
o	Lon.to: 180
o	Lat. from: 60
o	Lat. to: 90

•	Do not select Variables Constraints 

•	Select “Download and make local data source“ and enter Unique identifier UC11_AEROSOL_polar_2007

•	Click on “Download & Open Local”

 ### Specifications 

cate-2.0.0-dev.13
Windows 7 Professional

**Comment by forman** [comment]
@papesci please test + fix this asap as the error originated from untested/uncovered code in `cate/ds/local.py`:

      File "C:\Users\HClifton\cate-2.0.0.dev11\lib\site-packages\cate\core\ds.py", line 540, in open_dataset
        return data_source.open_dataset(time_range, region, var_names, monitor=monitor.child(20))
      File "C:\Users\HClifton\cate-2.0.0.dev11\lib\site-packages\cate\ds\local.py", line 192, in open_dataset
        msg += " for region {}".format(GeometryLike.format(region))
      File "C:\Users\HClifton\cate-2.0.0.dev11\lib\site-packages\cate\core\types.py", line 428, in format
        return value.wkt if value else ''
    AttributeError: 'str' object has no attribute 'wkt'

`region` was a string, but `GeometryLike.format(geom)` expects `geom` to be a shapely geometry with attribute `wkt` or None.

**Comment by papesci** [comment]
Bug fixed in branch [677](https://github.com/CCI-Tools/cate/tree/677-pp-region-formatl)

**Comment by HelenClifton** [comment]
Hi @papesci @forman I've just tested it with cate-2.0.0-dev.15
Now I'm seeing a different error when trying to download the dataset:
![aerosol](https://user-images.githubusercontent.com/29569434/41543755-060f3b3c-7307-11e8-966b-9368c2e460c0.PNG)
Here's the trace: [Traceback_aerosol.txt](https://github.com/CCI-Tools/cate/files/2111755/Traceback_aerosol.txt)

**Comment by papesci** [comment]
Hi @HelenClifton @forman it seem that the parameter 
data_vars=minimal'  passed in the function call 
`        ds = xr.open_mfdataset(files,
                               concat_dim=concat_dim,
                               autoclose=True,
                               coords='minimal',
                               data_vars='minimal',
                               chunks=chunks,
                               preprocess=preprocess,
                               **kwargs)`

cause the problem.

**Comment by forman** [comment]
@papesci Warning: don't simply fix that without regression testing all the other dataset types.

**Comment by papesci** [comment]
@HelenClifton  the bug fix is not present in release dev16 but is still in the master. I have been able to  reproduce the issue with dev16 but succeed with the master. I think we should wait for dev17

**Comment by HelenClifton** [comment]
@papesci  @forman Confirmed FIXED in cate-2.0.0-dev.17
