### ISSUE TITLE
Cannot download any sea level datasets with temporal constraints

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#686]
### Expected behavior

@papesci @hans-permana @forman Tried to download three esacci.SEALEVEL.mon.* with temporal constraints.
Expected them to download, as they had done with cate.2.0.0-dev.13

### Actual behavior

No matter which constraints I choose, I always get an error which looks like:

![sealevel](https://user-images.githubusercontent.com/29569434/41545892-b47366cc-730b-11e8-88fa-b850b218fb48.PNG)

Traceback here: 
[traceback_sealevel.txt](https://github.com/CCI-Tools/cate/files/2111879/traceback_sealevel.txt)

### Steps to reproduce the problem

see above

### Specifications 

cate-2.0.0-dev.15
Windows 7 professional

**Comment by papesci** [comment]
Hi @HelenClifton the Dataset you have requested is just single file which is the mean of the entire period from 1993-01-01 to 2015-12-31T23:59:59.  It cannot be reduced. However even expanding the time range the error appear. As a workaround we can download the dataset avoiding to use time restriction

**Comment by papesci** [comment]
@HelenClifton Hi, i have just verified that the datasets a single file which contain the mean from the beginning of the data up to  2016-12-02. The start time for this DS is 2016-12-12 while the end time is not specified so you can query setting -t 2016-12-02,2016-12-03 for example, you can actually  use any data after 2016-12-02.
