### ISSUE TITLE
Folder for new workspace is not created

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#690]
### Expected behavior

@forman , @hans-permana If a new workspace is created in the parent folder, then cate should create a new sub-folder.

### Actual behavior

A new sub-folder isn't created, so the first time the workspace is used there is an error:
![workspace2](https://user-images.githubusercontent.com/29569434/41714692-bbe66a58-7540-11e8-85d7-c197b8595950.PNG)

It's possible to work around this by manually creating the folder

### Steps to reproduce the problem

1. File->New Workspace 
2. Enter the name of a workspace for which folder doesn't already exist, e.g.

![workspace1](https://user-images.githubusercontent.com/29569434/41714698-c248ab22-7540-11e8-99bf-dde71ab71f84.PNG)

3. When the new workspace has been created, try to download a dataset to local
4. See error above 

This was originally reported in #419

### Specifications 

cate-2.0.0-dev.15
Windows 7 Professional
Also happens on mac

**Comment by hans-permana** [comment]
fixed by commit https://github.com/CCI-Tools/cate-desktop/commit/4c1b9a7546aaf040da231b31be25de5f50f36917
