### ISSUE TITLE
STYLES-Cate crashes(auto)-Compute valid min-max

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#694]
after computing correlation between aerosol and cloud; refer to }  spatial and/temporal subset problem #693

---- I noticed the display range-line is too  long with a mid value( see fig below)

![display range](https://user-images.githubusercontent.com/37798521/41923624-2a66b03e-7968-11e8-9691-502fb5d7a036.GIF)

An attempt to use the auto range button results in cate crushing(blank screen) BUT NO ERROR MESSAGE IN THE BACK END.

perhaps the operation uses too much memory as well if the values are too small and the operation has to determine the min-max and establish the average.
But I think the range-line is just too long.

Specifications 
cate 2.0.0-dev 15

**Comment by forman** [comment]
@hans-permana, can you reproduce this?

**Comment by Evadzi** [comment]
@hans-permana consider this steps below to reproduce this issue

-subset cloud(esacci-l......AASTR2) and aerosol (esacci_AEROSOLS_mon_L3C.AER_PRODUCTS_AATSR_Envisat_SU_04_21_R1.nc) data for any region(I used -140,-80,140,80)
- select the variables aaod for aerosol and cfc for cloud 
-co register the data 
cfc_coregis_spa_temp_subset = cate.ops.coregister(ds_master=aaod_spa_temp_subset, ds_slave=cfc_spa_temp_subset, method_us="nearest")

-run the correlation between the co registered cloud data and the aerosol data
cfc_aaod_correlation = cate.ops.pearson_correlation(ds_x=cfc_coregis_spa_temp_subset, ds_y=aaod_spa_temp_subset, var_x="cfc", var_y="AAOD550_mean")

-use the auto range compute function to display to view the correlation data (to view variations).

**Comment by hans-permana** [comment]
After following the steps above, I got identical correlation values of the resulting dataset. This leads to the slider unable to determine the min and max values to determine the range. This is a known issue in blueprint. A solution would be to probably disable the button when all the values are identical.
