### ISSUE TITLE
subset spatial 'mask' parameter shouldn't have resource selection enabled

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate#699]
``subset_spatial`` operation has a ``mask`` parameter which takes a ``Bool`` value to determine weather the output should be masked with the given region, or if the output should be cropped only to the bounding box of the given region.

In the operation invocation dialog this value has resource selection enabled leading to confusion - it can be understood that this is where the masking polygon should be provided:
![image](https://user-images.githubusercontent.com/9655353/42559038-37c19dca-84f3-11e8-87e5-26a9726b03fd.png)

**Comment by JanisGailis** [comment]
By default the value selection switch is set to 'value' selection. It only gets automatically set to 'resource' selection in a very specific scenario:

A ``GeoDataFrame`` region is read in and selected, the ``subset_spatial`` is then invoked through right-clicking on a region (any) on the map and selecting ``subset_spatial`` from the context menu.

**Comment by forman** [comment]
@JanisGailis Actually it should be `ds` that should receive the resource reference in this scenario, not `mask`. The code for this in TypeScript in the GUI, do you want to fix it on your own?

**Comment by JanisGailis** [comment]
I quickly looked at it, but couldn't understand how to fix it properly. I think the problem is that the `bool` type can theoretically be whatever, so all resources correspond to that type and the box gets populated. So, the proper fix would be to make sure that only resources of actual type 'bool' get added to the resource list.

**Comment by forman** [comment]
Assign it to me or Hans, if you prefer.

**Comment by JanisGailis** [comment]
Re-assign to Hans if needed. It would've been nice to take a shot at fixing this, but I guess my time is better spent working on operations.

**Comment by forman** [comment]
I agree, see #733
