### ISSUE TITLE
Enhance plotting capabilities

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#704]
### Expected behavior

Add to various `plot_xxx` operations

- [x] multiple variables per plot;
- [x] different line and point styles and colors;
- [x] allow plotting time series extracted from datasets (e.g. via. `tseries_point`);
- [x] allow plotting series of data frames.

### Actual behavior

Only one variable per plot, styles only via generic properties parameter which is a mostly undocumented dictionary of keyword arguments to matplotlib.

### Specifications 

Cate 1.0 ... 2.0.dev15

**Comment by Evadzi** [comment]
@forman @hans-permana 
Is it possible to import the *pearson_correlation_scalar*  operator to be part of this new operator; with the possibility of displaying the correlation values with the plot?

**Comment by forman** [comment]
Import?

**Comment by hans-permana** [comment]
I suggest @Evadzi to create a new issue because it is beyond the scope of this isuse.

**Comment by hans-permana** [comment]
Close via commit https://github.com/CCI-Tools/cate/commit/c678741ce44c1644e284c596fbfa05aa9dd08b1f
