### ISSUE TITLE
uc22 happy path CLI scripts - replace "compute" operation

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#719]
@JanisGailis, @VPriemer Re: Use case 22 happy path scripts at:
https://github.com/CCI-Tools/cate-e2e/blob/master/happy_path/scripts/uc22.bat
https://github.com/CCI-Tools/cate-e2e/blob/master/happy_path/scripts/uc22.sh

**compute** operation no longer exists in cate-2.0.0-dev.16, so happy path scripts will need updating accordingly (expect it would be replaced with **compute_dataset**)

**Comment by JanisGailis** [comment]
This should now be fixed

**Comment by HelenClifton** [comment]
@JanisGailis Thanks !
