### ISSUE TITLE
Error: "Cannot fetch information from CCI Open Data Portal server"

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#720]
### Expected behavior

@hans-permana , @papesci , @forman 
Tried to download a dataset. Expected it to download.

### Actual behavior

Error message: "Cannot fetch information from CCI Open Data Portal server"

![cannot fetch info](https://user-images.githubusercontent.com/29569434/42826130-37d0cb94-89d3-11e8-9f77-99b6ebdf6af9.PNG)

Traceback is here: 
[cannot fetch information.txt](https://github.com/CCI-Tools/cate/files/2202225/cannot.fetch.information.txt)

However when trying again a few minutes later (and after having restarted the GUI), the error was not seen and the dataset downloaded successfully.

### Steps to reproduce the problem

Note: These are the steps that were followed when the error was seen, however they do not guarantee to reproduce the error, because it doesn't always occur
1. Open GUI 
2. Create a new workspace 
3. Select data source: esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1
4. Click on “Download and/or open remote dataset”. In “Download Data Source” window:
  •	Select Time Constraint and enter start time of 2010-01-01 and end time of 2010-12-31
  •	Select Region Constraint, enter:
    o	Lon. from:  -100
    o	Lon. from: 80
    o	Lat. from: -90
    o	Lat. to: 90
•	Select Variables Constraint, select variable cfc from the list 
•	Select “Download and make local data source“ and enter Unique identifier UC22_cloud
•	Click on “Download & Open Local”

### Specifications 

cate-2.0.0-dev.16
Windows 7 Professional

**Comment by papesci** [comment]
@HelenClifton it looks a network glitch or a temporary service downtime. 
The Error trace report a network timeout but the service become available meanwhile your second successful attempt to download the data.  It could be also a temporary overload of the remote data store service.

**Comment by forman** [comment]
So can we close it?

**Comment by HelenClifton** [comment]
@papesci @forman It can be closed as it cannot be reproduced
