### ISSUE TITLE
I/O error when downloading dataset

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#721]
### Expected behavior
Selected SST dataset for download. Expected it to download.

### Actual behavior

The download stopped part of the way through, with the following error message:

![sst io error](https://user-images.githubusercontent.com/29569434/42867610-a74c3e86-8a5f-11e8-82a2-9c6d486a9df8.PNG)
traceback: 
[SST IO Error.txt](https://github.com/CCI-Tools/cate/files/2204874/SST.IO.Error.txt)

Download of the same dataset was attempted again the next day, and then it completed without any problems.

### Steps to reproduce the problem
Steps are below, however note that the I/O error only happens occasionally.
@papesci , @forman , @hans-permana 
This issue has been raised so the problem can be tracked in case it occurs again.

1. Open GUI 
2. Create a new workspace 
3. Select data source: esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1.
4. Click on “Download and/or open remote dataset”
5. In “Download Data Source” window:
•	Select Time Constraint and enter start time of 2006-01-01 and end time of 2007-12-31
•	Select Region Constraint, enter:
o	Lon. from:  -175
o	Lon. from: -115
o	Lat. from: -10
o	Lat. to: 10
•	Select Variables Constraint, select variables analysed_sst and analysis_error from the list 
•	Select “Download and make local data source“ and enter Unique identifier UC06_SST_2006_2007
•	Click on “Download & Open Local”

### Specifications 

cate-2.0.0-dev.16
Windows 7 Professional

**Comment by papesci** [comment]
Hi @HelenClifton i didn't find problems to download this data. 
Do you still get I/O error on this data ?

**Comment by HelenClifton** [comment]
@papesci I'm not able to reproduce it either. It only happens occasionally.
I'm closing this for now, it can be re-opened if the problem is seen again
