### ISSUE TITLE
CCI Sea Level MSLAMPH data not correctly displayed

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#722]
### Expected behavior
@forman , @hans-permana , @papesci , @Evadzi, @JanisGailis 
Opened CCI data source esacci.SEALEVEL.mon_IND.MSLAMPH.multi-sensor.multi-platform.MERGED.2-0.r1
Expected it to display

### Actual behavior

Display is shifted by 180deg.
World view:
![world view 11](https://user-images.githubusercontent.com/29569434/42874264-2ddd4c3c-8a70-11e8-9637-d21fc6cdb9ea.PNG)
World view with dataset layer (phase) superimposed:
![dataset11](https://user-images.githubusercontent.com/29569434/42874338-648e41c8-8a70-11e8-8882-dad106a56268.PNG)

Same behaviour is seen when a regional subset is applied.

It is similar to issue #661. (However that one is now fixed and esacci.SEALEVEL.mon.IND.MSLTR.* dataset is displaying correctly)

### Steps to reproduce the problem

As above

### Specifications 

cate-2.0.0-dev.16
Windows 7 Professional

**Comment by HelenClifton** [comment]
hi @forman Please review the above info from @papesci regarding the dataset, and assign this issue to the correct person for the fix. Thanks !

**Comment by forman** [comment]
@HelenClifton , @papesci That's really weird, as turning lon=0...360 into lon=-180...+180 is part of the data normalization step when opening datasets, see also #717.
