### ISSUE TITLE
Errors on Windows and Mac build possibly due to failed code signing

### ISSUE THREAD

**Issue by hans-permana** [CCI-Tools/cate#726]
### Expected behavior

Builds should pass without any errors and Windows & Mac installers should be signed.

### Actual behavior

Builds produced an error: 
```
Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
From previous event:
    at CancellationToken.createPromise (/Users/travis/build/CCI-Tools/cate-installer/cate-desktop/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at /Users/travis/build/CCI-Tools/cate-installer/cate-desktop/node_modules/builder-util/src/nodeHttpExecutor.ts:23:44
From previous event:
.
.
.
.
```
Complete logs can be viewed [here](https://travis-ci.org/CCI-Tools/cate-installer/jobs/404397216) (Mac) and [here](https://ci.appveyor.com/project/ccitools/cate-installer) (Windows). 

Also, the resulting installers did not seem to be signed, prompting some security confirmation from users when executed.

### Specifications 

* **electron-build version**: 19.56.2
* **electron-updater version**: 2.20.1

**Comment by hans-permana** [comment]
Reported the issue here https://github.com/electron-userland/electron-builder/issues/3121 due to suspicion that it may be electron builder issue.

**Comment by forman** [comment]
Problem was at Dropbox, where we host the certificates. The Dropbox download URL parameter suddenly stopped working. 

Fix: 

    CSC_LINK=https://www.dropbox.com/**/*.p12?dl=1

had to be turned into

    CSC_LINK=https://dl.dropbox.com/**/*.p12
