### ISSUE TITLE
Unit test failed when using dask 0.18.2

### ISSUE THREAD

**Issue by hans-permana** [CCI-Tools/cate#727]
### Expected behavior

All unit tests should pass.

### Actual behavior

1 unit test `TestExternal.test_dask()` failed after dask is updated to 0.18.2

### Steps to reproduce the problem

1. create cate-env and upgrade dask to `0.18.2`
2. run all tests

### Specifications 

**dask**: 0.18.2

**Comment by JanisGailis** [comment]
With latest ``environment.yml`` we request ``19.0 >= dask``, with which tests work fine. Closing this, unless there's an explicit reason for supporting the (likely buggy) ``0.18.2`` version.
