### ISSUE TITLE
Cate Desktop, version 2.0.0-dev.17 failed to start on Ubuntu due to missing .so

### ISSUE THREAD

**Issue by dzelge** [CCI-Tools/cate#729]
__Expected__

Cate desktop should run on Ubuntu

__Actual behaviour__

Cate does not start reporting the following error:

`/home/helge/cate-desktop/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
`

__Solution__

seems to be installing libgconf-2-4:

`sudo apt-get install libgconf-2-4`

**Comment by hans-permana** [comment]
as also reported here https://github.com/electron/electron/issues/1518 . Workaround is by including libgconf-2-4 to AppImage bundle

**Comment by dzelge** [comment]
Add an installation section to the cate-desktop Readme using the installer. Currently there is only a section compiling cate desktop from source.
