### ISSUE TITLE
GUI doesn't reopen after closing it

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#765]
### Expected behavior
@forman, @hans-permana 
Cate GUI is open
Selected File->Exit
Selected Exit again to confirm
GUI closes
Double-click Cate Desktop.
Expect GUI to re-open.

### Actual behavior

GUI doesn't re-open.
Looking in Windows Task Manager, can see two cate desktop processes still running.

![gui1](https://user-images.githubusercontent.com/29569434/45962703-ffe4e200-c010-11e8-86bc-ef5bdbd4bcf7.PNG)

As a workaround, these can be ended manually using "End Process" in Windows Task Manager, then the GUI will open.

Another feature is that if the user selects "Do not ask me again" in the cate exit dialog
![gui2](https://user-images.githubusercontent.com/29569434/45962928-8c8fa000-c011-11e8-9426-4ab419207722.PNG)
then the problem goes away after the GUI has been opened then closed again.

### Steps to reproduce the problem

See above. 
Looks similar to #636

### Specifications 

Cate-2.0.0-dev.19
Windows 7 Professional

**Comment by forman** [comment]
Thanks Helen. This is so frustrating. Thought this was fixed. Can't think of any code changes in that part.

**Comment by forman** [comment]
Can't reproduce this. What if you wait a minute before starting Cate Desktop once more?

**Comment by forman** [comment]
@HelenClifton was it a clean install or an auto-update from dev18 to dev19. Are you sure that dev18 behaved different?

**Comment by forman** [comment]
@HelenClifton can you please confirm, this does *not* happen, if you exit using the main window close icon.
Have you tested Mac and Linux?

**Comment by forman** [comment]
Here are possibly related Electron issues:

* https://github.com/electron/electron/issues/1322
* https://github.com/electron/electron/issues/2312

**Comment by forman** [comment]
Just compared the log files from the Cate Desktop development version. Left is window close, right is exit from file menu (calls `electron.app.quit()`:

![image](https://user-images.githubusercontent.com/206773/46018391-0e4b0080-c0da-11e8-8c54-998ecbfed9ad.png)

Looks as it should! In both case, the backend is shut down.

And here is the packaged Cate Desktop. Again left is window close, right is exit from file menu:

![image](https://user-images.githubusercontent.com/206773/46018499-47837080-c0da-11e8-8e1d-008da8f64630.png)

**Comment by forman** [comment]
oops

**Comment by forman** [comment]
@HelenClifton we have a fix in 2.0.0-dev.20, to be released later today.

**Comment by HelenClifton** [comment]
@forman Confirmed fixed in dev.20. closing it.
