### ISSUE TITLE
Cannot subset  and display data correctly for longitudes with interval>180 

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#787]
Hi @JanisGailis 

### Expected behavior

*I expect cate 2.0.0. dev-20 to subset and display data correctly for longitudes with interval>180*

### Actual behavior

*Cate 2.0.0. dev-20 is unable to display correctly  data for longitudes with interval>180*

### Steps to reproduce the problem
*You can test with any esa cci data*
```import cate.ops

# Step 1
ds_1 = cate.ops.open_dataset(ds_id="esacci.SEALEVEL.mon.IND.MSLAMPH.multi-sensor.multi-platform.MERGED.2-0.r1", region="-150,-40,30,70", force_local=True)

# Step 2
ds_2 = cate.ops.open_dataset(ds_id="esacci.SEALEVEL.mon.IND.MSLAMPH.multi-sensor.multi-platform.MERGED.2-0.r1", region="-150,-40,31,70", force_local=True)```
  

### Specifications 

*cate 2.0.0. dev-20, Windows 10*

**Comment by JanisGailis** [comment]
This really should work!

**Comment by JanisGailis** [comment]
@Evadzi I can confirm that this happens when ``open_dataset`` is used with a regional constraint.

A workaround is to open the dataset without a regional constraint, and then do ``subset_spatial`` on it.

**Comment by Evadzi** [comment]
@JanisGailis Yes! the `subset_spatial` works but not with the `open_dataset`
