### ISSUE TITLE
Cannot coregister soil moisture datasets

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#810]
### Expected behavior

@JanisGailis @forman Expect to be able to coregister soil mositure datasets with other ECV datasets

### Actual behavior

Using the following datasets:
**esacci.SOILMOISTURE.day.L3S.SSMS.multi-sensor.multi-platform.ACTIVE.03-2.r1**, 2004-01-01,2004-05-01
**esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.PASSIVE.03-2.r1**,  2004-01-01,2004-05-01

Coregister with:
**esacci.AEROSOL.mon.L3.AAI.multi-sensor.multi-platform.ms_uvai.1-5-7.r1**, 2004-01-01, 2005-12-31
**esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1**, 2004-01-01, 2005-01-01
**esacci.CLOUD.mon.L3C.CLD_PRODUCTS.AVHRR.multi-platform.AVHRR-PM.2-0.r1**, 2004-01-01, 2004-05-01
**esacci.FIRE.day.L4.BA.multi-sensor.multi-platform.MERIS.v4-1.r1**, 2005-01-01, 2005-05-01
e**sacci.OC.mon.L3S.K_490.multi-sensor.multi-platform.MERGED.2-0.r1**, 2004-01-01, 2004-05-01
e**sacci.OC.mon.L3S.CHLOR_A.multi-sensor.multi-platform.MERGED.2-0.r1**, 2004-01-01, 2004-05-01, lat=[-10,10], lon=[-175,-115] 
**esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1**, 2007-01-01, 2007-03-31
**esacci.OZONE.day.L3S.TC.multi-sensor.multi-platform.MERGED.fv0100.r1**, 2004-01-01,2004-01-15, lat=[-10,10], lon=[-175,-115] 
**esacci.SEALEVEL.mon.IND.MSLAMPH.multi-sensor.multi-platform.MERGED.2-0.r1**
**esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1**, 2004-01-01, 2004-02-31
**esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1**, 2004-01-01, 2005-12-31, lat=[-10,10], lon=[-175,-115] 

In all cases there is an "Invalid Input" dialog:
![capture](https://user-images.githubusercontent.com/29569434/48258200-6fb9fb00-e40c-11e8-9fbd-34e06a7d4874.PNG)

Same happens when soil misture dataset is either master dataset or slave dataset.

### Steps to reproduce the problem

1. Download / open one of the two soil moisture datasets above 
2. Download / open  one of other ECV datasets from list above
3. Select operation **coregister** , select datasets and keep other parameters as default

### Specifications 

cate-2.0.0-dev.21
Wndows 7 Professional

**Comment by JanisGailis** [comment]
@HelenClifton Thanks for the Issue report! I appreciate the list of failing datasets.

The good news are - I can not reproduce this on the current master branch. All sm datasets - active, passive and combined coregister fine with aerosol.

@forman Should you re-release the `dev21`? As it seems that it's still `dev20` `cate-core` code running in the latest dev release!

**Comment by forman** [comment]
I'll release dev22 now.

**Comment by JanisGailis** [comment]
@HelenClifton I can not reproduce this on `dev23`. Closing this, please re-open if persists.
