### ISSUE TITLE
Shift in the position of generated data(spatial_subset)

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#817]
### Expected behavior

perform spatial subset using specified lon, lat  values

### Actual behavior

Cate executes the spatial subset process but shift in the position of the generated data
...see..
![image](https://user-images.githubusercontent.com/37798521/49231127-8cd16080-f3f1-11e8-9814-ab8c5e3b98e3.png)

### Steps to reproduce the problem

1. lc = cate.ops.open_dataset(ds_id="esacci.LC.5-yrs.L4.LCCS.multi-sensor.multi-platform.Map.1-6-1.r1", force_local=True)

2. lc_subset_spatial = cate.ops.subset_spatial(ds=lc, region="-20,-20,20,20")

### Specifications 

Cate 2.0.0-dev 23, Windows 10

**Comment by forman** [comment]
Maybe linked to LC data issue #804

**Comment by JanisGailis** [comment]
What happens if `plot_map` is used on the subset? Might need to subset an even smaller chunk for plot_map to work.
