### ISSUE TITLE
Cannot download SST dataset - I/O error

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#823]
### Expected behavior

Tried to download the SST dataset which is used for the use case 6 happy path, using cate GUI.

### Actual behavior

@forman Using cate-2.0.0-dev.23, it has not been possible to download the dataset because there has always been an I/O error before the download has completed. (It has also happened with CLI)
The errors occur at different times after the downlaod has started. An example is below:
![capture](https://user-images.githubusercontent.com/29569434/50081949-a6431c80-01e7-11e9-917d-87441b49b195.PNG)
and here's the traceback: 
[Traceback.txt](https://github.com/CCI-Tools/cate/files/2685562/Traceback.txt)

The last test of the use case 6 was done at the beginning of October using cate-2.0.0-dev.20. At that time , the SST dataset downloaded successfully, although it took about an hour.
Recently though, download speeds have seemed a lot slower (in general, not just this dataset)

### Steps to reproduce the problem

1.  Highlight data source: esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1
Click on “Download and/or open remote dataset”

In “Download Data Source” window:
•	Select Time Constraint and enter start time of 2006-01-01 and end time of 2007-12-31

•	Select Region Constraint, enter:
o	Lon. from:  -175
o	Lon. from: -115
o	Lat. from: -10
o	Lat. to: 10

•	Select Variables Constraint, select variables analysed_sst and analysis_error from the list 

•	Select “Download and make local data source“ and enter Unique identifier UC06_SST_2006_2007

•	Click on “Download & Open Local”

2. Wait ! 

### Specifications 

cate-2.0.0-dev.23
Windows 7 Professional

**Comment by forman** [comment]
All these bugs seem to come from a single root cause that applies when we do spatial subsets and consequently use OPeNDAP. Now the list of related issues 

* #822
* #818 
* #816
* #783

**Comment by forman** [comment]
@HelenClifton there is no problem, if you uncheck "Download and make local data source":

![image](https://user-images.githubusercontent.com/206773/50168313-65343080-02eb-11e9-8273-94f5502118ea.png)
