### ISSUE TITLE
Cate Desktop installation on Windows fails

### ISSUE THREAD

**Issue by dzelge** [CCI-Tools/cate#831]
### Expected behavior

Cate Desktop installs on Windows 10 when backend needs to be installed.

### Actual behavior

Cate installation fails with the following message:

```
failedg environment: ...working... 

UnsatisfiableError: The following specifications were found to be in conflict:
  - cate-cli=2.0.0.dev24 -> conda=4.5.11
  - conda[version='>=4.5.12']
Use "conda info <package>" to see the dependencies for each package.



Setup failed: Installation of Python package cate 2.0.0.dev24 did not succeed.
```

![grafik](https://user-images.githubusercontent.com/42441761/51176105-5e81e480-18bc-11e9-90e5-d529c95714db.png)

### Steps to reproduce the problem

1. Download cate desktop setup v 2.0.0-dev24
2. Double click to install and wait for the installation to fail
3. Check log

### Specifications 

*Provide information such as the version of the project, operating system, or hardware.*

**Comment by dzelge** [comment]
![grafik](https://user-images.githubusercontent.com/42441761/51175947-f6cb9980-18bb-11e9-8ac5-b9c880f765c8.png)

**Comment by dzelge** [comment]
This download produces a miniconda env using conda v4.5.12 which then conflicts with cate-cli's conda version 4.5.11.

![grafik](https://user-images.githubusercontent.com/42441761/51177055-e79a1b00-18be-11e9-9d9e-4b9f8d3a8968.png)

**Comment by forman** [comment]
Still don't understand why we can't fix the conda version. Maybe because we don't create a separate env but use the Minconda base env?

**Comment by forman** [comment]
We should fix the Miniconda version too. This really gets on my nerves.

**Comment by dzelge** [comment]
Which would make sense. We fix the conda version in the environment.yml which means we probably should better fix the miniconda version we install as well.

**Comment by forman** [comment]
Guess, I got it. Cate Desktop invokes the following after successful Minicionda install:

    conda install --yes -c ccitools -c conda-forge conda cate-cli=2.0.0.dev24

Note the extra `conda` dependency without version spec. This defaults to 4.5.12 in latest Miniconda. But our requirement is =4.5.11. That's what's probably causing the issue.

Still, why now? Why haven't we seen this issue before.
