### ISSUE TITLE
Cate Desktop - problem with Automatic setup (username with space)

### ISSUE THREAD

**Issue by Acastro11** [CCI-Tools/cate#841]
### Expected behavior

Cate Desktop (2.0.0-dev.23) to install on my Windows PC, where current username has a space character, using the Automatic setup.

### Actual behavior

A problem prevents the automatic setup: the username contains a character.
![Cate_desktop_screenshot](https://user-images.githubusercontent.com/49022507/55147758-472a6780-5147-11e9-8b6e-45e007e529c6.JPG)

### Steps to reproduce the problem

1. Download cate-desktop-setup-2.0.0-dev.23 
2. Double click on it and wait
3.  The Cate Desktop Setup window shown above will appear, indicating a problem in the automatic setup

### Specifications 

Windows 10 Enterprise, version 1709, OS Build 16299.967
Processor Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz 2.50 GHz
Installed RAM 8GB (7.89 usable)
System type 64-bit operating system, x64-based processor
cate-desktop-setup-2.0.0-dev.23 
[cate-desktop.log](https://github.com/CCI-Tools/cate/files/3017276/cate-desktop.log)

**Comment by hans-permana** [comment]
Hi @Acastro11, this is a known issue which unfortunately has to be solved from Conda (see #568). 

As a workaround, I think your idea of selecting another directory with no spaces (eg. `C:\Users\Public`) should work, provided this directory is fully read- and writeable by your user. I recommend you to try this. 

We are monitoring the situation with Conda. Hopefully, one day they address this issue of having spaces in  the environment path.

**Comment by forman** [comment]
We are no longer supporting Cate Desktop. Please use the web app from now on: https://cate.climate.esa.int/.
