### ISSUE TITLE
Failed to install of version 2.0.0-dev.23 as "automatic setup"

### ISSUE THREAD

**Issue by TomLav** [CCI-Tools/cate#842]
### Expected behavior

Install of cate-desktop on a Linux Ubuntu 18.04 Bionic Beaver.

### Actual behavior

Installation fails with error (see attached log).

### Steps to reproduce the problem

1. download cate-desktop-2.0.0-dev.23-x86_64.AppImage
2. chmod 755 cate-desktop-2.0.0-dev.23-x86_64.AppImage
3. ./cate-desktop-2.0.0-dev.23-x86_64.AppImage > 

### Specifications 

uname -a
Linux pc4897 4.18.0-16-generic #17~18.04.1-Ubuntu SMP Tue Feb 12 13:35:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

###  Attachments:

1. log: ./cate-desktop-2.0.0-dev.23-x86_64.AppImage > cate_install.log 2>&1
[cate_install.log](https://github.com/CCI-Tools/cate/files/3024663/cate_install.log)

2. screenshot (note the reference to dev.22 while the image is for dev.23).
![cate_screehshot](https://user-images.githubusercontent.com/9883832/55264811-f1a0a880-5275-11e9-985f-fd64cc66d7e7.png)

**Comment by hans-permana** [comment]
this is probably related to #843 . New release of Cate v2.0.0-dev.26 should fix this issue. See here for a new installation https://github.com/CCI-Tools/cate-desktop/releases/tag/v2.0.0-dev.26

**Comment by TomLav** [comment]
Installation of dev.26 worked on the Bionic Beaver system. Case closed. Thank you.
