### ISSUE TITLE
Installation failed: Unsatisfiable Error

### ISSUE THREAD

**Issue by hans-permana** [CCI-Tools/cate#843]
### Expected behavior

Cate installs successfully

### Actual behavior

Cate failed to install with "UnsatisfiableError" 
![image](https://user-images.githubusercontent.com/7643370/55278344-9508c080-533d-11e9-9763-a316c529c04b.png)

### Steps to reproduce the problem

1. Install cate by double clicking `cate-desktop-setup-2.0.0-dev.26.exe` file 
2. Select default installation 

### Specifications 

Windows 10 Pro
Cate 2.0.0-dev.25

**Comment by hans-permana** [comment]
A more careful investigation suggests that this is due to dependency clash caused by gdal 2.3.2.

**Comment by forman** [comment]
No longer supporting Cate Desktop.
