### ISSUE TITLE
Installation failed with "connect EACCES 104.16.130.3:443"

### ISSUE THREAD

**Issue by retostockli** [CCI-Tools/cate#845]
Fails with: Setup failed: connect EACCES 104.16.130.3:443 during running setup on Windows 7 without Admin priviledges (Run Setup Tasks).

Reproduce by:
1. start cate-desktop-setup-2.0.0.exe
2.  Security Warning of Windows 7: click "run" this file
3. Select "automatic setup" 

System:
- Windows 7
- Corporate Connectivity (So we are on our local LAN even when abroad)
- We have a http proxy (proxy.meteoswiss.ch:8080)

**Comment by forman** [comment]
Sorry for this, Cate definitely has problems running behind some proxies, see also #627. 

Note, that an upcoming version of Cate will have remote servers, hence no longer force you to install a Python environment.
