### ISSUE TITLE
GUI installation fails on mac with Anaconda2 pre-installed

### ISSUE THREAD

**Issue by nelerey** [CCI-Tools/cate#847]
### Expected behavior 
Cate GUI installs succesfully.

### Actual behavior
- Cate GUI fails to install using .dmg file. Error message similar to #657 on Windows and #639 on Mac. 
- This happens when attempting to install in a new environment of existing Anaconda2 installation as well as when choosing the first option (installing a "new" cate).
- Problem persisted after removing Anaconda**2** (which in hindsight might not have been removed entirely).

### Solution
installation finally succeeded after installing Anaconda**3** and subsequently installing cate in a new environment with $ conda install -c ccitools cate

### Steps to reproduce the problem
download .dmg file and run; see above

### Specifications 
macOS Mojave 10.14.3
[cate-desktop-2.0.0.dmg](https://github.com/CCI-Tools/cate-desktop/releases/tag/v2.0.0)
[cate-desktop-2.0.0-dev.25.dmg](https://github.com/CCI-Tools/cate-desktop/releases/tag/v2.0.0-dev.25)  (nb: the "How to install" section should be updated with dev.25 instead of dev.23)
(Anaconda2 was already installed on the system.)

**Comment by forman** [comment]
We are no longer supporting Cate Desktop. Please use the web app from now on: https://cate.climate.esa.int/.
