### ISSUE TITLE
Pearson Correlation fails

### ISSUE THREAD

**Issue by njwag** [CCI-Tools/cate#850]
### Expected behavior

I expect Cate to create a map of pixel-wise correlation coefficients as shown below:

![image](https://user-images.githubusercontent.com/27773566/60824055-39a26600-a1a9-11e9-93db-e1d5be1f0bec.png)

The two variables that should be correlated are burned area and soil moisture. I am using the pearson_correlation function in the Cate GUI.

### Actual behavior

First I used a timeseries of soil moisture and burned area. I got the following error message:

_The provided variables burned_area and sm do not have the same shape, Pearson correlation can not be performed. Please review operation documentation_

I thought it has something to do with the unequal length of both time series. So I tried to correlate the data for a single date and got the following error message:

_The length of the time dimension should not be less than three to run the calculation._

### Steps to reproduce the problem

1. Import MODIS Burned Area Grid and Soil Moisture (Combined Product)
2. Coregister both datasets with Fire product as master
3. Run pearson_correlation in the GUI.

### Specifications 

I am using Cate Desktop 2.0.0 on a Windows 10 computer with 8GB RAM.

**Comment by Evadzi** [comment]
@njwag ,
Although the fire data is daily, it has 2 entries per month whereas the soil moisture data has entries for each day.
For your correlation to work the data must have same temporal and spatial constraint.
-first aggregated the data into monthly-mean
-check the spatial extent, then
-perform the correlation. 
It works!!

try the following:
1. set region e.g.=lon, lat :"-35,-40", "60,40"
2. fire_month_aggre = cate.ops.temporal_aggregation(ds=ds_fire)
3. sm_month_aggre = cate.ops.temporal_aggregation(ds=ds_sm)
4.pearson_cor = cate.ops.pearson_correlation(ds_x=fire_month_aggre, ds_y=sm_month_aggre, var_x="burned_area", var_y="sm")

![fire_sm_cor](https://user-images.githubusercontent.com/37798521/60906449-6e7cee80-a277-11e9-8ce2-c2e42d80b67a.png)

**Comment by njwag** [comment]
Thank you, that worked! Best regards
