### ISSUE TITLE
CCI Data Store crashes when reading data sources

### ISSUE THREAD

**Issue by TonioF** [CCI-Tools/cate#894]
### Expected behavior

Cate should be able to read in all data sources from the CCI ODP store.

### Actual behavior

Cate crashes, as an XML-file could not be parsed.

### Steps to reproduce the problem

E.g.:
data_store = EsaCciOdpDataStore()
data_source = data_store.query(ds_id='esacci.CLOUD.month.L3C.CLD_PRODUCTS.multi-sensor.Envisat.MERIS-AATSR.2-0.r1')[0]

### Specifications 

This behaviour occurs with the new version of the CCI store based on opensearch.

**Comment by forman** [comment]
Fixed!
