### ISSUE TITLE
Support data sets with zonal means

### ISSUE THREAD

**Issue by TonioF** [CCI-Tools/cate#902]
The CCI ODP Data Store provides data sets that have no longitude information and instead of a latitude dimension, a dimension named "latitude_centers". These datasets need to be displayed too, preferably as bands spanning a latitude region. To do this, it is necessary to rename "latitude_centers" to "lat" and to insert a new dimension "lon" that covers the globe.

**Comment by AliceBalfanz** [comment]
Implemented by PR #905
