### ISSUE TITLE
Support data sets with time information in file name only

### ISSUE THREAD

**Issue by TonioF** [CCI-Tools/cate#904]
Currently, cate relies on that a time dimension is provided in data sets that shall be concatenated. If time information is only provided in the metadata, a new dimension can be creted from this information. However, Cate can not yet deal with datasets that have their time information in their filenames only.

**Comment by AliceBalfanz** [comment]
Please have another look, the changes cause a problem for of your PR #906 
esacci.OZONE.mon.L3.LP.GOMOS.Envisat.GOMOS_ENVISAT.v0001.r1
esacci.OZONE.mon.L3.LP.GOMOS.Envisat.GOMOS_ENVISAT.v0001.r1
esacci.OZONE.mon.L3.LP.SCIAMACHY.Envisat.SCIAMACHY_ENVISAT.v0001.r1
esacci.OZONE.mon.L3.LP.MIPAS.Envisat.MIPAS_ENVISAT.v0001.r1
esacci.OZONE.mon.L3.LP.SMR.ODIN.SMR_ODIN.v0001.r1
esacci.OZONE.mon.L3.LP.SMR.ODIN.MZM.v0001.r1

**Comment by AliceBalfanz** [comment]
Fixed by TonioF  with Commits on Jul 10, 2020
