### ISSUE TITLE
Various datasets failing with IndexError('list index out of range')

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate#946]
When trying to open certain datasets (14 in total), the error IndexError('list index out of range') appears. E.g. for: 

esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.2-1.sst
esacci.AEROSOL.yr.L3C.AER_PRODUCTS.ATSR-2.Envisat.ATSR2-ENVISAT-ENS_ANNUAL.v2-6.r1

**Comment by AliceBalfanz** [comment]
After investigating, the source of this error is now known: 
For some datasets the variables may not unambiguously specified. This happens if a Open-Search Feature consists of more than one datasets which not all have the same variables. This issue is already known, and there is a draft of a solution, however only reachable via the test endpoints of odp.

**Comment by TonioF** [comment]
Issue has been solved with https://github.com/CCI-Tools/cate/pull/990 .
