### ISSUE TITLE
Failing saving to disk with KeyError('geospatial_lat_max'))

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate#961]
The dataset esacci.SST.day.L4.SSTskin.Unspecified.Unspecified.GMPE.2-0.r1 fails at saving to disk with a 
KeyError('geospatial_lat_max'))

This is due to the retrieval of geospatial information from the remote_dataset's attributes and for that particular dataset this information does not exists. This should not lead to an error as this information may be easily retrieved from the datasets data itself.

**Comment by TonioF** [comment]
Solved by #962
