### ISSUE TITLE
Support Sea Ice data in Zarr Data Store

### ISSUE THREAD

**Issue by TonioF** [CCI-Tools/cate#998]
The Zarr Data Store contains data from the ODP that has been converted into the zarr format. There is one Sea Ice dataset in the Zarr data store. For the purposes of this issue, we say that a dataset is supported when
1. it can be opened in cate
2. it can be opened in cate with a spatial subset
3. its content can be written to disk
4. its data can be displayed in cate

Card is delayed due to corrupt input data.

**Comment by pont-us** [comment]
Paused because data not available in Zarr data store yet.

**Comment by TonioF** [comment]
Dataset is crossing both prime and anti meridian, therefore no geocoding can be derived. In consequence, it is not possible to open a spatial subset. Further, the spatial dimensions are not given as lat / lon, therefore it cannot be displayed in Cate.

![image](https://user-images.githubusercontent.com/1598254/119476844-b9f6f380-bd4e-11eb-828e-cf099f805be3.png)
